#!/bin/sh
# This file generated automatically by newlib

D=`dirname $0`
DIR=`cd $D;( [ -x /usr/local/bin/awd ] && awd ) || pwd`
#
# check to see if there is a Makefile in the build directory
#
if test -f Makefile
then
  echo -n "Makefile exists.  Clean directory and proceed ? [n*/y] "
  read answer
  if test "${answer-n}" = y
  then
    forced=yes
  else
    exit 1
  fi
fi

SRC_DIR=`cd $DIR/..;( [ -x /usr/local/bin/awd ] && awd ) || pwd`
if [ ! -e Makefile ] || test $forced
then
  /bin/perl -pe "s|^(SHELL.*)$|\1\nUSER_SRC = $SRC_DIR|" $DIR/Makefile.lib \
     > Makefile
else
  echo "Makefile already exists."
fi
