# HOW TO RUN
#  OMP_NUM_THREADS=4 ./PlotEventData Events03.root
#
# Setting the linker and compiler flags and options
INCLUDE   = $(shell root-config --cflags)
LIBS      = $(shell root-config --libs) 
CXX       = g++
CCFLAGS   = -Wall -O2 #-fopenmp

# Define binary file name.
BINS = train classify

# Define targets
all: train classify 

train: % : %.cpp #$(HEADS)/*.h
	$(CXX) $(CCFLAGS) PndKnnTrain.cpp $< $(INCLUDE) $(LIBS) -o $@
	@echo "Done"

classify: % : %.cpp #$(HEADS)/*.h
	$(CXX) $(CCFLAGS) PndKnnClassify.cpp $< $(INCLUDE) $(LIBS) -o $@
	@echo "Done"

clean:
	rm -f $(BINS) *~

cleanall:
	rm -f $(BINS) *~ *.so *.d  *.pdf *.ps *.root
