cmake_minimum_required(VERSION 2.6)
SET(CMAKE_CXX_FLAGS "-g -m32")
#SET(CMAKE_VERBOSE_MAKEFILE ON)
PROJECT(myProject)
ENABLE_TESTING()
INCLUDE_DIRECTORIES($ENV{ROOTSYS}/include)
				
	
SET(DICT		myDict.cxx)
SET(LINKDEF		LinkDef.h)
SET(SOURCES		TCevent.cxx TCcluster.cxx TCtrack.cxx)
SET(DICT_HEADERS        TCevent.h TCtrack.h TCcluster.h)		
SET(MAIN		main.cxx)
SET(MYLIB		MY)
SET(EXE			main)


SET(SOURCES ${SOURCES} ${DICT})


FIND_PROGRAM(ROOT_CINT_EXECUTABLE
	NAMES rootcint
	PATHS $ENV{ROOTSYS}/bin
	NO_DEFAULT_PATH)

ADD_CUSTOM_COMMAND(OUTPUT ${DICT}
	COMMAND ${ROOT_CINT_EXECUTABLE}
      	ARGS -f ${DICT} -c -DHAVE_CONFIG_H ${INCLUDE_DIRECTORIES}
      	${DICT_HEADERS} ${LINKDEF}
      	DEPENDS ${DICT_HEADERS})

ADD_LIBRARY(${MYLIB} SHARED ${SOURCES})

#add ROOT lib
Execute_process(COMMAND root-config --glibs --cflags
	OUTPUT_VARIABLE ROOT_LIBS
    	OUTPUT_STRIP_TRAILING_WHITESPACE)



TARGET_LINK_LIBRARIES(${MYLIB} ${ROOT_LIBS})


# executable
ADD_EXECUTABLE(${EXE} ${MAIN})
TARGET_LINK_LIBRARIES(${EXE} ${MYLIB})
TARGET_LINK_LIBRARIES(${EXE} ${ROOT_LIBS})



