#!/bin/bash 
################################################################
## script for running sim&rec for trk reconstruction performance
## [with pixels sensors set-up!]
## 05/10/2012
## A.Karavdina
################################################################

#mergedHits=true
numEv=10000
#pbeam=11.91

#numEv=100
#for pbeam in 15 1.5 4.06 8.9 11.91
#for pbeam in 15 8.9 1.5
for pbeam in 15
do
momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`
pathG=${VMCWORKDIR}/macro/lmd/tmpOutnewDesign/noFilterInCA_4aTaskForAll/mom_${momStr}/
mkdir -p ${pathG}
  #for numTrks in 20 1 2 3 4 5 7 10 15
   for numTrks in 10
    do
    path=${pathG}/${numTrks}trks
    mkdir -p ${path}

    mergedHits=true
    addMS=true
#trkCandcut=false
# root -l -b -q runLumiPixel0SimBox.C\(${numEv},0,${pbeam},"\"${path}\"",0,-2212,${numTrks},3562\)
# root -l -b -q runLumiPixel1Digi.C\(${numEv},0,"\"${path}\""\)
 #root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\) &> ${path}/logPixel_HitRec_${numTrks}trks_mergedHits_${pbeam}GeV
 #root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\) &> ${path}/logPixel_HitMerge_${numTrks}trks_mergedHits_${pbeam}GeV

    ##CA & Minuit
    trkCandcut=true
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits},${trkCandcut}\) &> ${path}/logPixel_CA_${numTrks}trks_mergedHits_${pbeam}GeV

    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\) 
 #&> ${path}/logPixel_MinuitFit_${numTrks}trks_mergedHits_${pbeam}GeV
     ### Filter tracks
    root -l -b -q runLumiPixel4aFilter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)   &> ${path}/logFilterCA_${numTrks}trks
    mv ${path}/Lumi_Track_0.root ${path}/Lumi_notFilteredTrack_0.root
    cp ${path}/Lumi_TrackFiltered_0.root ${path}/Lumi_Track_0.root
    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\) 
#&> ${path}/logPixel_GEANE_${numTrks}trks_mergedHits_${pbeam}GeV
    cd ${VMCWORKDIR}/buildPanda/bin
   # ./hits_study -s 0 -n ${numEv} -path ${path} -out ${path}/ResidualsHist_${numTrks}_${pbeam}_mergedHits_${mergedHits}_addMS_${addMS}.root -st 1 -mh ${mergedHits}
    ./pixelrec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -mh 1 -v 0 -path ${path}  
#&> ${path}/logPIXEL_CA_Minuit_mc_rec_match_${pbeam}GeV



   cd ${VMCWORKDIR}/macro/lmd
   mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${pathG}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit.root
     root -l -b -q runLumiPixel7QA.C\(${numEv},0,"\"${path}\"",0,${pbeam}\)
     mv ${path}/Lumi_QA_0.root ${path}/Lumi_QA_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit.root

    # ##Trk-Follow & Minuit
     trkCandcut=true
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"Follow\"",true,${mergedHits},${trkCandcut}\) &> ${path}/logPixel_Follow_${numTrks}trks_mergedHits_${pbeam}GeV
    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
   ### Filter tracks
    root -l -b -q runLumiPixel4aFilter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)  
# &> ${path}/logFilterFollow_${numTrks}trks
    mv ${path}/Lumi_Track_0.root ${path}/Lumi_notFilteredTrack_0.root
    cp ${path}/Lumi_TrackFiltered_0.root ${path}/Lumi_Track_0.root

    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
    cd ${VMCWORKDIR}/buildPanda/bin
    ./pixelrec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam}  -mh 1 -v 0 -path ${path} 
#&> ${path}/logPIXEL_Follow_Minuit_mc_rec_match_${pbeam}GeV
    cd ${VMCWORKDIR}/macro/lmd
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${pathG}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit.root
     root -l -b -q runLumiPixel7QA.C\(${numEv},0,"\"${path}\"",0,${pbeam}\)
     mv ${path}/Lumi_QA_0.root ${path}/Lumi_QA_Follow_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit.root
   #  addMS=false
   #  root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)
   #  ## CA & Kalman
   #  root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\)
   #  root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\)
   #  time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\) &> ${path}/logPixel_KalmanFit_${numTrks}trks_mergedHits_${pbeam}GeV
   #  time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
   #  cd ${VMCWORKDIR}/build/bin
   # # ./hits_study -s 0 -n ${numEv} -path ${path} -out ${path}/ResidualsHist_${numTrks}_${pbeam}_mergedHits_${mergedHits}_addMS_${addMS}.root -st 1 -mh ${mergedHits}
   #  ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1  -mh 1 -v 0 -path ${path}  >> ${path}/logPIXEL_Follow_Minuit_mc_rec_match_${pbeam}GeV
  
   #  cd ${VMCWORKDIR}/macro/lmd
   #  mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_KalmanFillter_${pbeam}.root

   #  ##Trk-Follow & Kalman
   #  root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"Follow\"",true,${mergedHits}\)
   #  time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\)
   #  time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
   #  cd ${VMCWORKDIR}/build/bin
   #  ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1  -mh 1 -v 0 -path ${path}
   #  cd ${VMCWORKDIR}/macro/lmd
   #  mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_KalmanFillter_${pbeam}.root

   #  # ##don't merge hits
   #  mergedHits=false
  
   #  addMS=true
   #  root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)
   #  ##CA & Minuit
   #  root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\)  >> ${path}/logPixel_CA_${numTrks}trks_singleHits_${pbeam}GeV
   #  root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
   #  root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
   #  cd ${VMCWORKDIR}/build/bin
   #  ./hits_study -s 0 -n ${numEv} -path ${path} -out ${path}/ResidualsHist_${numTrks}_${pbeam}_mergedHits_${mergedHits}_addMS_${addMS}.root -st 1 -mh ${mergedHits}
   #  ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1 -mh 0 -v 0 -path ${path}

   #  cd ${VMCWORKDIR}/macro/lmd
   #  mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit_${pbeam}.root

   #  addMS=false
   #  root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)
   #  ## CA & Kalman
   #  root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\)
   #  time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\)
   #  time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
   #  cd ${VMCWORKDIR}/build/bin
   #  ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1 -mh 0 -v 0 -path ${path}
   #  cd ${VMCWORKDIR}/macro/lmd
   #  mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_KalmanFillter_${pbeam}.root
done
root -l -b -q Anastasia/test_macros/TrksAlgoResults.C\("\"${pathG}\""\)
done
exit
