#!/bin/bash
time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,1)' >> log0_1trk
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")' >> log1_1trk
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")' >> log2_1trk
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)' >> logCA_1trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")' >> log4_1trk
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")' >> log5_1trk
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 1 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_1trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)'  >> logFollow_1trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 1 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_1trk_11_91GeV.root



time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,2)' 
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)' >> logCA_2trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 2 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_2trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)'  >> logFollow_2trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")' 
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 2 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_2trk_11_91GeV.root

time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,3)'
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")' 
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)'  >> logCA_3trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")' 
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 3 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_3trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)' >> logFollow_3trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 3 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_3trk_11_91GeV.root


time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,4)'
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)'  >> logCA_4trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 4 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_4trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)'  >> logFollow_4trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 4 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_4trk_11_91GeV.root

time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,5)'
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)'  >> logCA_5trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 5 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_5trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)'  >> logFollow_5trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 5 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_5trk_11_91GeV.root

time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,10)'
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)'  >> logCA_10trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 10 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_10trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)'  >> logFollow_10trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 10 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_10trk_11_91GeV.root

time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,15)'
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)'  >> logCA_15trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")' 
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 15 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_15trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)'  >> logFollow_15trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 15 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_15trk_11_91GeV.root

time root -l -b -q 'runLumi0SimBox.C(100000,11.91,"tmpOutput",0,-2212,20)' 
time root -l -b -q 'runLumi1Digi.C(100000,0,"tmpOutput")' 
time root -l -b -q 'runLumi2Reco.C(100000,0,"tmpOutput")'  
time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "CA",true)'  >> logCA_20trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'  
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")' 
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 20 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_new_100000_20trk_11_91GeV.root

time root -l -b -q 'runLumi3Finder.C(100000,0,"tmpOutput", 0, "Follow",true)'  >> logFollow_20trk
time root -l -b -q 'runLumi4Fitter.C(100000,0,"tmpOutput")'
time root -l -b -q 'runLumi5Geane.C(100000,11.91,0,"tmpOutput")'
cd /data/FAIRsorf/pandaroot/trunk/build/bin
./rec_mc_match -s 0 -n 100000 -t 20 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
cd /home/akaravdina/lmdMacro
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_new_100000_20trk_11_91GeV.root

mkdir /myResults/LUMI_Trk/newCA_oldDesign/100000events
mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0_* /myResults/LUMI_Trk/newCA_oldDesign/100000events/.
mv log*  /myResults/LUMI_Trk/newCA_oldDesign/100000events/.
# # ##########################################################################################

# time root -l -b -q 'runLumi0SimBox.C(40000,1.5,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,1.5,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 1.5 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_1_5GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,4.06,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,4.06,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 4.06 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_4_06GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,8.9,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,8.9,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 8.9 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_8_9GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,11.91,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,11.91,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_11_91GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,15,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,15,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 15 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_15GeV.root

      
# time root -l -b -q 'runLumi0SimBox.C(40000,1.5,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,1.5,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 1.5 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_1_5GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,4.06,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,4.06,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 4.06 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_4_06GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,8.9,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,8.9,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 8.9 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_8_9GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,11.91,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,11.91,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_11_91GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,15,"tmpOutput",0,-2212,4)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,15,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 15 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_4trk_15GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,1.5,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,1.5,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 1.5 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_1_5GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,4.06,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,4.06,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 4.06 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_4_06GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,8.9,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,8.9,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 8.9 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_8_9GeV.root



#mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_11_91GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,15,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,15,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 15 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_15GeV.root

      
# time root -l -b -q 'runLumi0SimBox.C(40000,1.5,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,1.5,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 1.5 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_1_5GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,4.06,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,4.06,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 4.06 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_4_06GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,8.9,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,8.9,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 8.9 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_8_9GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,11.91,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,11.91,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_11_91GeV.root

# time root -l -b -q 'runLumi0SimBox.C(40000,15,"tmpOutput",0,-2212,1)'
# time root -l -b -q 'runLumi1Digi.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi2Reco.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi3Finder.C(40000,0,"tmpOutput", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(40000,0,"tmpOutput")'
# time root -l -b -q 'runLumi5Geane.C(40000,15,0,"tmpOutput")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 40000 -mom 15 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutput"
# cd /home/akaravdina/lmdMacro
# mv tmpOutput/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root /myResults/LUMI_Trk/EffAndRes/Lumi_out_MC_and_REC_trks_matches_with_IDs0_4_8mrad_40000_1trk_15GeV.root
exit
