#!/bin/bash 
################################################################
## script for running sim&rec for trk reconstruction performance
## [with pixels sensors set-up!]
## 05/10/2012
## A.Karavdina
################################################################

#mergedHits=true
numEv=20000
#numEv=10
#pbeam=11.91

#numEv=100
#for pbeam in 15 1.5 4.06 8.9 11.91
#for pbeam in 15 8.9 1.5
for pbeam in 1.5 4.06 8.9 11.91 15
do
momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`
pathG=${VMCWORKDIR}/macro/lmd/tmpOutnewDesign/noFilterInCA_4aTaskForAll/mom_${momStr}/
mkdir -p ${pathG}

for CAparam in 0.0000001 0.000001 0.000002 0.000004 0.000006 0.000008 0.00001 0.00002 0.00004 0.00006 0.00008 0.0001
#for CAparam in 0
do
CAparamStr=`echo $CAparam | sed -e '{ s/\./_/g; }'`
   
    for numTrks in 5 10 1
    do
      
    path=${pathG}/${numTrks}trks
    mkdir -p ${path}

    mergedHits=true
    addMS=true
#trkCandcut=false
# root -l -b -q runLumiPixel0SimBox.C\(${numEv},0,${pbeam},"\"${path}\"",0,-2212,${numTrks},3562\)
# root -l -b -q runLumiPixel1Digi.C\(${numEv},0,"\"${path}\""\)
#  root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\) &> ${path}/logPixel_HitRec_${numTrks}trks_mergedHits_${pbeam}GeV
#  root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\) &> ${path}/logPixel_HitMerge_${numTrks}trks_mergedHits_${pbeam}GeV
    rm ${path}/Lumi_TCand_0.root
    rm ${path}/Lumi_Track_0.root
    rm ${path}/Lumi_TrackFiltered_0.root
    rm ${path}/log*
    ##CA & Minuit
    trkCandcut=true
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits},${trkCandcut},${CAparam}\) &> ${path}/logPixel_CA_${numTrks}trks_mergedHits_${pbeam}GeV

    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\) 
 #&> ${path}/logPixel_MinuitFit_${numTrks}trks_mergedHits_${pbeam}GeV
     ### Filter tracks
    root -l -b -q runLumiPixel4aFilter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)   &> ${path}/logFilterCA_${numTrks}trks
    mv ${path}/Lumi_Track_0.root ${path}/Lumi_notFilteredTrack_0.root
    cp ${path}/Lumi_TrackFiltered_0.root ${path}/Lumi_Track_0.root
    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\) 
#&> ${path}/logPixel_GEANE_${numTrks}trks_mergedHits_${pbeam}GeV
    cd ${VMCWORKDIR}/buildPanda/bin
   # ./hits_study -s 0 -n ${numEv} -path ${path} -out ${path}/ResidualsHist_${numTrks}_${pbeam}_mergedHits_${mergedHits}_addMS_${addMS}.root -st 1 -mh ${mergedHits}
    ./pixelrec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -mh 1 -v 0 -path ${path}  
#&> ${path}/logPIXEL_CA_Minuit_mc_rec_match_${pbeam}GeV
   cd ${VMCWORKDIR}/macro/lmd
   mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${pathG}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_psi$CAparamStr.root
done
done
root -l -b -q Anastasia/test_macros/TrksCApsiValueSearch.C\("\"${pathG}\""\) 
done
exit
