#!/bin/bash 
################################################################
## script for running sim&rec for LMD
## [with pixels sensors set-up!]
## 13/11/2012
## A.Karavdina
################################################################
pathG=${VMCWORKDIR}/macro/lmd/testPixel/memory/
mkdir -p ${pathG}
scaleP=1
scaleM=1
#MOM=(15 1.5 4.06 8.9 11.91) #GeV
MOM=(1.5) #GeV
MOMN=${#MOM[@]}
  for (( jp=0;jp<$MOMN;jp++)); do
      pbeam=${MOM[${jp}]}
      momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`
      path=${pathG}/mom_${momStr}/
      mkdir -p ${path}
      numTrks=1
      mergedHits=true
      numEv=1000000
##    numEv=100
      cd /panda/pandaroot/macro/lmd
      root -l -b -q runLumiPixel0SimBox.C\(${numEv},0,${pbeam},"\"${path}\"",0,-2212,${numTrks}\)
      root -l -b -q runLumiPixel1Digi.C\(${numEv},0,"\"${path}\""\)

      rm ${path}/Lumi_Geane_0.root
      rm ${path}/Lumi_reco_0.root
      rm ${path}/Lumi_recoMerged_0.root
      rm ${path}/Lumi_TCand_0.root
      rm ${path}/Lumi_Track_0.root
      useMSerr=false
      root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${useMSerr},false\)
# ### Merge hits
	  root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\)
# ### CA can use merged or single(not merged) hits
# ### change "CA" --> "Follow" if you want to use Trk-Following as trk-search algorithm
# ### NB: Trk-Following can't use single(not merged) hits!
# ### change true --> false if you don't want to use missing search algorithm
     root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\)
	 cp ${path}/FairRunInfo_Lumi_TCand_0.root ${path}/FairRunInfo_Lumi_TCand_CA_0.root

    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"Follow\"",true,${mergedHits}\)
	 cp ${path}/FairRunInfo_Lumi_TCand_0.root ${path}/FairRunInfo_Lumi_TCand_Follow_0.root

##Minuit
	 root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
	 cp ${path}/FairRunInfo_Lumi_Track_0.root ${path}/FairRunInfo_Lumi_Track_Minuit_0.root

#     ### or Kalman Fillter with GEANE
root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits},"\"GEANE\"",$scaleP,$scaleM\) 
cp ${path}/FairRunInfo_Lumi_Track_0.root ${path}/FairRunInfo_Lumi_Track_GEANE_0.root


#     ### or Kalman Fillter with RK
root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits},"\"RK\"",$scaleP,$scaleM\) 
cp ${path}/FairRunInfo_Lumi_Track_0.root ${path}/FairRunInfo_Lumi_Track_RK_0.root

#    use GEANE for back-propagation
   root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
cp ${path}/FairRunInfo_Lumi_Geane_0.root ${path}/FairRunInfo_Lumi_BP_Geane_0.root

# # compare MC trk params and reconstructed trk params and much more...
    cd ${VMCWORKDIR}/buildPanda/bin
   ./simple_mc_rec_match -s 0 -n ${numEv} -mom ${pbeam} -v 0 -path ${path}
   mv ${path}/Lumi_compare_MC_and_REC_trks_0.root  ${path}/Lumi_compare_MC_and_REC_trks_KALMANRK_BPGEANE.root 

   cd /panda/pandaroot/macro/lmd
   rm ${path}/Lumi_Geane_0.root
 ## use Runge-Kutta for back-propagation
   root -l -b -q runLumi5RungeKutta.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
   cp ${path}/FairRunInfo_Lumi_Geane_0.root ${path}/FairRunInfo_Lumi_BP_RK_0.root

   cd ${VMCWORKDIR}/buildPanda/bin
  ./simple_mc_rec_match -s 0 -n ${numEv} -mom ${pbeam} -v 0 -path ${path}
  mv ${path}/Lumi_compare_MC_and_REC_trks_0.root  ${path}/Lumi_compare_MC_and_REC_trks_KALMANGEANE_BPRK.root 

  done

