stages:
 - CDASH

before_script:
  - source generateDartConfig.sh

# Templates for various FAIR versions
# If a machine has all tags it can run
.current:
  stage: CDASH
  variables:
    FAIRSOFT_VERSION: may18
    FAIRROOT_VERSION: v18.0.4
  tags:
   - may18
   - v18.0.4

.future:
  stage: CDASH
  variables:
    FAIRSOFT_VERSION: jul19
    FAIRROOT_VERSION: v18.0.7
  tags:
   - jul19
   - v18.0.7

# Experimental build, including tests, mostly upon finished merge
current:full:
  extends: .current
  script:
    - source Dart.sh Experimental Dart-$CI_JOB_NAME.cfg
  only:
    - branches@PandaRootGroup/PandaRoot
  except:
    - schedules

future:full:
  extends: .future
  script:
    - source Dart.sh Experimental Dart-$CI_JOB_NAME.cfg
  only:
    - branches@PandaRootGroup/PandaRoot
  except:
    - schedules

# Continuous build for all pushes of users
current:continuous:
  extends: .current
  script:
    - source Dart.sh Continuous Dart-$CI_JOB_NAME.cfg
  except:
    - branches@PandaRootGroup/PandaRoot
    - schedules

future:continuous:
  extends: .future
  script:
    - source Dart.sh Continuous Dart-$CI_JOB_NAME.cfg
  except:
    - branches@PandaRootGroup/PandaRoot
    - schedules

# Nightly builds & tests, available from gitlab schedule
current:nightly:
  extends: .current
  script:
    - source Dart.sh Nightly Dart-$CI_JOB_NAME.cfg
  only:
    # refs: is needed here to work with varables
    refs:
      - branches@PandaRootGroup/PandaRoot
    variables:
      - $MODEL == "NIGHTLY"

future:nightly:
  extends: .future
  script:
    - source Dart.sh Nightly Dart-$CI_JOB_NAME.cfg
  only:
    # refs: is needed here to work with varables
    refs:
      - branches@PandaRootGroup/PandaRoot
    variables:
      - $MODEL == "NIGHTLY"

# Profile builds, tests & profilinge, available from gitlab schedule
current:profile:
  extends: .current
  script:
    - source Dart.sh Profile Dart-$CI_JOB_NAME.cfg
  only:
    # refs: is needed here to work with varables
    refs:
      - branches@PandaRootGroup/PandaRoot
    variables:
      - $MODEL == "PROFILE"

future:profile:
  extends: .future
  script:
    - source Dart.sh Profile Dart-$CI_JOB_NAME.cfg
  only:
    # refs: is needed here to work with varables
    refs:
      - branches@PandaRootGroup/PandaRoot
    variables:
      - $MODEL == "PROFILE"
