stages:
 - configure
 - test

cache:
  untracked: true

configure:current:
  stage: configure
  script: source generateDartConfig.sh
  variables:
    FAIRSOFT_VERSION: may16p1
    FAIRROOT_VERSION: v-17.10b
  tags:
    - may16p1
    - v-17.10

configure:future:
  stage: configure
  script: source generateDartConfig.sh
  variables:
    FAIRSOFT_VERSION: oct17
    FAIRROOT_VERSION: dev
  tags:
   - oct17
   - FairRoot_dev

cdash:current:full:
  stage: test
  script: source Dart.sh Experimental Dart.cfg
  only:
  - branches@PandaRootGroup/PandaRoot
  dependencies:
   - configure:current
  
  tags:
   - may16p1
   - v-17.10

cdash:future:full:
  stage: test
  script: source Dart.sh Experimental Dart.cfg
  only:
  - branches@PandaRootGroup/PandaRoot
  dependencies:
    - configure:future
  tags:
    - oct17
    - FairRoot_dev

cdash:current:continuous:
  stage: test
  script: source Dart.sh Continuous Dart.cfg
  except:
  - branches@PandaRootGroup/PandaRoot
  dependencies:  
   - configure:current
  
  tags:
   - may16p1
   - v-17.10

cdash:future:continuous:
  stage: test
  script: source Dart.sh Continuous Dart.cfg
  except:
  - branches@PandaRootGroup/PandaRoot
  dependencies:
    - configure:future
  tags:
    - oct17
    - FairRoot_dev
