#$ -wd /tmp 
#$ -j y
#$ -V

cd $TMPDIR

. $FAIRLIBDIR/../config.sh

hera=$VMCWORKDIR"/macro/softrig"
_target=$hera"/data/"

mode=9999
nEvts=1000
dec="pp_DpDm_Dp_Kpipi_incl.dec"
mom=12.3485
res="pbarpSystem0"

sig=1

if test "$1" != ""; then
  mode=$1
fi

if test "$2" != ""; then
  nEvts=$2
fi

if test "$3" != ""; then
  dec=$3
fi

if test "$4" != ""; then
  mom=$4
fi

if test "$5" != ""; then
  res=$5
fi

if test "$dec" == "DPM"; then
  sig=0
else
  dec=$hera"/"$dec
fi

outprefix=$TMPDIR"/M"$mode"_"$SGE_TASK_ID

echo $TMPDIR
root -l -q -b -w $hera"/"prod_fsim.C\(\"$outprefix\",\"$dec\",$mom,$nEvts,\"$res\",$mode,$SGE_TASK_ID\) &> $outprefix"_fsim.log"


# Move the data to the persistent storage
cp -v $TMPDIR/M* $_target 
# Evacuate the log-file
cp -v $SGE_STDOUT_PATH $_target/$JOB_ID.log
