#!/bin/bash
# Select queue
#$ -l short=TRUE,h_vmem=3000M
# Divert output
#$ -o /nfs/nas/data/panda/tpc/SIM/evtmix/logs/
# Write error in same file
#$ -j y

cd /nfs/hicran/project/panda/SIM/sneubert/buildFair/
. config.sh
cd /nfs/hicran/project/panda/SIM/sneubert/pandaroot/trunk/

DATADIR=/nfs/nas/data/panda/tpc/SIM/evtmix/noDistort
INFILE=$DATADIR/phys_JPsiPiPi.skim.noDD.raw.root
BKGFILE=$DATADIR/DPM.noDD.raw.root

NEVENTS=50
let STARTEVENT=$SGE_TASK_ID*$NEVENTS

NBKGEVTS=1000
JOBNAME="evtmix$NBKGEVTS"


root -b -q macro/tpc/runEvtMixDigi.C\(\"$INFILE\",\"$JOBNAME\",$STARTEVENT,$NEVENTS,\"$BKGFILE\",$NBKGEVTS\)