/********************************************************************
* CbmPlaneDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CbmPlaneDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableCbmPlaneDict();
extern void G__cpp_setup_inheritanceCbmPlaneDict();
extern void G__cpp_setup_typetableCbmPlaneDict();
extern void G__cpp_setup_memvarCbmPlaneDict();
extern void G__cpp_setup_globalCbmPlaneDict();
extern void G__cpp_setup_memfuncCbmPlaneDict();
extern void G__cpp_setup_funcCbmPlaneDict();
extern void G__set_cpp_environmentCbmPlaneDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "CbmGeoPlane.h"
#include "CbmGeoPlanePar.h"
#include "CbmPlane.h"
#include "CbmPlanePoint.h"
#include "CbmPlaneContFact.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CbmPlaneDictLN_TClass;
extern G__linked_taginfo G__CbmPlaneDictLN_TBuffer;
extern G__linked_taginfo G__CbmPlaneDictLN_TMemberInspector;
extern G__linked_taginfo G__CbmPlaneDictLN_TObject;
extern G__linked_taginfo G__CbmPlaneDictLN_TNamed;
extern G__linked_taginfo G__CbmPlaneDictLN_TObjArray;
extern G__linked_taginfo G__CbmPlaneDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__CbmPlaneDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__CbmPlaneDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TString;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmGeoSet;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmGeoPlane;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmParSet;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmParamList;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmParGenericSet;
extern G__linked_taginfo G__CbmPlaneDictLN_TClonesArray;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmGeoPlanePar;
extern G__linked_taginfo G__CbmPlaneDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CbmPlaneDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CbmPlaneDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__CbmPlaneDictLN_TVector3;
extern G__linked_taginfo G__CbmPlaneDictLN_TLorentzVector;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmModule;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmVolume;
extern G__linked_taginfo G__CbmPlaneDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__CbmPlaneDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmDetector;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmPlanePoint;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmPlane;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmMCPoint;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmContainer;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmContFact;
extern G__linked_taginfo G__CbmPlaneDictLN_CbmPlaneContFact;

/* STUB derived class for protected member access */
