/********************************************************************
* PndJRGenCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PndJRGenCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablePndJRGenCint();
extern void G__cpp_setup_inheritancePndJRGenCint();
extern void G__cpp_setup_typetablePndJRGenCint();
extern void G__cpp_setup_memvarPndJRGenCint();
extern void G__cpp_setup_globalPndJRGenCint();
extern void G__cpp_setup_memfuncPndJRGenCint();
extern void G__cpp_setup_funcPndJRGenCint();
extern void G__set_cpp_environmentPndJRGenCint();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "PndReaction.hh"
#include <algorithm>
//namespace std { }
//using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PndJRGenCintLN_TClass;
extern G__linked_taginfo G__PndJRGenCintLN_TBuffer;
extern G__linked_taginfo G__PndJRGenCintLN_TMemberInspector;
extern G__linked_taginfo G__PndJRGenCintLN_TObject;
extern G__linked_taginfo G__PndJRGenCintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__PndJRGenCintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PndJRGenCintLN_TString;
extern G__linked_taginfo G__PndJRGenCintLN_TClonesArray;
extern G__linked_taginfo G__PndJRGenCintLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__PndJRGenCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PndJRGenCintLN_TH1D;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PndJRGenCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__PndJRGenCintLN_TVector3;
extern G__linked_taginfo G__PndJRGenCintLN_TDecayChannel;
extern G__linked_taginfo G__PndJRGenCintLN_TParticle;
extern G__linked_taginfo G__PndJRGenCintLN_TGenPhaseSpace;
extern G__linked_taginfo G__PndJRGenCintLN_PndReaction;

/* STUB derived class for protected member access */
