//
// File generated by /cvmfs/fairroot.gsi.de/fairsoft/apr13/bin/rootcint at Tue Jul 15 16:47:58 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PndJRGenCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PndJRGenCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void PndReaction_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_PndReaction(void *p);
   static void deleteArray_PndReaction(void *p);
   static void destruct_PndReaction(void *p);
   static void streamer_PndReaction(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PndReaction*)
   {
      ::PndReaction *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PndReaction >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PndReaction", ::PndReaction::Class_Version(), "./PndReaction.hh", 29,
                  typeid(::PndReaction), DefineBehavior(ptr, ptr),
                  &::PndReaction::Dictionary, isa_proxy, 0,
                  sizeof(::PndReaction) );
      instance.SetDelete(&delete_PndReaction);
      instance.SetDeleteArray(&deleteArray_PndReaction);
      instance.SetDestructor(&destruct_PndReaction);
      instance.SetStreamerFunc(&streamer_PndReaction);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PndReaction*)
   {
      return GenerateInitInstanceLocal((::PndReaction*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PndReaction*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *PndReaction::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PndReaction::Class_Name()
{
   return "PndReaction";
}

//______________________________________________________________________________
const char *PndReaction::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PndReaction*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PndReaction::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PndReaction*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PndReaction::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PndReaction*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PndReaction::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PndReaction*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void PndReaction::Streamer(TBuffer &R__b)
{
   // Stream an object of class PndReaction.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void PndReaction::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PndReaction.
      TClass *R__cl = ::PndReaction::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BeamTarget", &BeamTarget);
      R__insp.InspectMember(BeamTarget, "BeamTarget.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "filename", &filename);
      R__insp.InspectMember(filename, "filename.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "weight", &weight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PrimaryVtx", &PrimaryVtx);
      R__insp.InspectMember(PrimaryVtx, "PrimaryVtx.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "VtxResolution", &VtxResolution);
      R__insp.InspectMember(VtxResolution, "VtxResolution.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "VtxResFlag", &VtxResFlag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEvt", &fEvt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "activeCnt", &activeCnt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "StaticBR", &StaticBR);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PoleMass", &PoleMass);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Elastic", &Elastic);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*MassHistos[100]", &MassHistos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PID[100]", PID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numHistos", &numHistos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*PWHistos[100][20]", &PWHistos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PartialWaves[100][22]", PartialWaves);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PWindex", &PWindex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PartStable[100]", PartStable);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PStabindex", &PStabindex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PolarIndex", &PolarIndex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PolarID[100]", PolarID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Polar[100]", Polar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Asym[100]", Asym);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "DC", &DC);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_PndReaction(void *p) {
      delete ((::PndReaction*)p);
   }
   static void deleteArray_PndReaction(void *p) {
      delete [] ((::PndReaction*)p);
   }
   static void destruct_PndReaction(void *p) {
      typedef ::PndReaction current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_PndReaction(TBuffer &buf, void *obj) {
      ((::PndReaction*)obj)->::PndReaction::Streamer(buf);
   }
} // end of namespace ROOT for class ::PndReaction

/********************************************************
* PndJRGenCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePndJRGenCint();

extern "C" void G__set_cpp_environmentPndJRGenCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PndReaction.hh");
  G__cpp_reset_tagtablePndJRGenCint();
}
#include <new>
extern "C" int G__cpp_dllrevPndJRGenCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PndReaction */
static int G__PndJRGenCint_597_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PndReaction* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PndReaction(
*((TParticle*) G__int(libp->para[0])), *((TVector3*) G__int(libp->para[1]))
, (char*) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) PndReaction(
*((TParticle*) G__int(libp->para[0])), *((TVector3*) G__int(libp->para[1]))
, (char*) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PndReaction(*((TParticle*) G__int(libp->para[0])), *((TVector3*) G__int(libp->para[1])));
     } else {
       p = new((void*) gvp) PndReaction(*((TParticle*) G__int(libp->para[0])), *((TVector3*) G__int(libp->para[1])));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PndReaction(*((TParticle*) G__int(libp->para[0])));
     } else {
       p = new((void*) gvp) PndReaction(*((TParticle*) G__int(libp->para[0])));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->Loop((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->GetWeight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->UseStaticBR();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->UsePoleMass();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PndReaction*) G__getstructoffset())->UseElasticDXC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PndReaction*) G__getstructoffset())->Decay((TParticle*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((PndReaction*) G__getstructoffset())->SelectChannel((TParticle*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->BranchRatio((TParticle*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PartialWidth((TParticle*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PW((TParticle*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->TotalWidth((TParticle*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 6:
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PhaseSpace((Double_t) G__double(libp->para[0]), (Int_t*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])
, (Int_t) G__int(libp->para[4]), (Int_t) G__int(libp->para[5])));
      break;
   case 5:
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PhaseSpace((Double_t) G__double(libp->para[0]), (Int_t*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])
, (Int_t) G__int(libp->para[4])));
      break;
   case 4:
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PhaseSpace((Double_t) G__double(libp->para[0]), (Int_t*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])));
      break;
   case 3:
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PhaseSpace((Double_t) G__double(libp->para[0]), (Int_t*) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->Prob((Int_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((PndReaction*) G__getstructoffset())->InitHisto((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->BreitWigner((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->SampleMass((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->SampleLifetime((TParticle*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((PndReaction*) G__getstructoffset())->Stable((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PoleWidth((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PCM((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->DefinePartialWaves((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PndReaction*) G__getstructoffset())->PWWeight((TGenPhaseSpace*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->SetStable((Long_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->doElastic();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->SetPolarization((Long_t) G__int(libp->para[0]), (Long_t) G__int(libp->para[1])
, (Float_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->SetDecayAsymmetry((Long_t) G__int(libp->para[0]), (Long_t) G__int(libp->para[1])
, (Float_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PndReaction::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PndReaction::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PndReaction::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PndReaction::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PndReaction*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PndReaction::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PndReaction::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PndReaction::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PndJRGenCint_597_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PndReaction::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PndJRGenCint_597_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PndReaction* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PndReaction(*(PndReaction*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PndReaction G__TPndReaction;
static int G__PndJRGenCint_597_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PndReaction*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PndReaction*) (soff+(sizeof(PndReaction)*i)))->~G__TPndReaction();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PndReaction*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PndReaction*) (soff))->~G__TPndReaction();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PndJRGenCint_597_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PndReaction* dest = (PndReaction*) G__getstructoffset();
   *dest = *(PndReaction*) libp->para[0].ref;
   const PndReaction& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PndReaction */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPndJRGenCint {
 public:
  G__Sizep2memfuncPndJRGenCint(): p(&G__Sizep2memfuncPndJRGenCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPndJRGenCint::*p)();
};

size_t G__get_sizep2memfuncPndJRGenCint()
{
  G__Sizep2memfuncPndJRGenCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePndJRGenCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction))) {
     PndReaction *G__Lderived;
     G__Lderived=(PndReaction*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction),G__get_linked_tagnum(&G__PndJRGenCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePndJRGenCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PndJRGenCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PndJRGenCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PndJRGenCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PndJRGenCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__PndJRGenCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__PndJRGenCintLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PndReaction */
static void G__setup_memvarPndReaction(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction));
   { PndReaction *p; p=(PndReaction*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TParticle),-1,-1,4,"BeamTarget=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TString),-1,-1,4,"filename=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"weight=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TVector3),-1,-1,4,"PrimaryVtx=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TVector3),-1,-1,4,"VtxResolution=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"VtxResFlag=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TClonesArray),-1,-1,4,"fEvt=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"activeCnt=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"StaticBR=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"PoleMass=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"Elastic=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TH1D),-1,-1,4,"MassHistos[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"PID[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"numHistos=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TH1D),-1,-1,4,"PWHistos[100][20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"PartialWaves[100][22]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"PWindex=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("Long_t"),-1,4,"PartStable[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("Long_t"),-1,4,"PStabindex=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("Long_t"),-1,4,"PolarIndex=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("Long_t"),-1,4,"PolarID[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"Polar[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"Asym[100]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"DC=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PndJRGenCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPndJRGenCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPndReaction(void) {
   /* PndReaction */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction));
   G__memfunc_setup("PndReaction",1111,G__PndJRGenCint_597_0_1, 105, G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction), -1, 0, 3, 1, 1, 0, 
"u 'TParticle' - 0 - BT u 'TVector3' - 0 'TVector3()' VR "
"C - - 0 '\"jim++output.root\"' OutFile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Loop",410,G__PndJRGenCint_597_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - nEvts", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWeight",904,G__PndJRGenCint_597_0_3, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UseStaticBR",1065,G__PndJRGenCint_597_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UsePoleMass",1105,G__PndJRGenCint_597_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UseElasticDXC",1233,G__PndJRGenCint_597_0_6, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "Use Elastic Differential Cross Section for pbar-b", (void*) NULL, 0);
   G__memfunc_setup("Decay",486,G__PndJRGenCint_597_0_7, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "U 'TParticle' - 0 - mother", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SelectChannel",1305,G__PndJRGenCint_597_0_8, 85, G__get_linked_tagnum(&G__PndJRGenCintLN_TDecayChannel), -1, 0, 1, 1, 1, 0, "U 'TParticle' - 0 - mother", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BranchRatio",1101,G__PndJRGenCint_597_0_9, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"U 'TParticle' - 0 - mother i - 'Int_t' 0 - channel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PartialWidth",1229,G__PndJRGenCint_597_0_10, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"U 'TParticle' - 0 - mother i - 'Int_t' 0 - DecChan", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PW",167,G__PndJRGenCint_597_0_11, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"U 'TParticle' - 0 - mother i - 'Int_t' 0 - DecChan", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TotalWidth",1028,G__PndJRGenCint_597_0_12, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'TParticle' - 0 - mother", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PhaseSpace",989,G__PndJRGenCint_597_0_13, 100, -1, G__defined_typename("Double_t"), 0, 6, 1, 1, 0, 
"d - 'Double_t' 0 - ecm I - 'Int_t' 0 - array "
"i - 'Int_t' 0 - nPart i - 'Int_t' 0 '0' ch "
"i - 'Int_t' 0 '0' indx i - 'Int_t' 0 '0' S", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Prob",403,G__PndJRGenCint_597_0_14, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - PDGCode d - 'Double_t' 0 - Mass", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitHisto",923,G__PndJRGenCint_597_0_15, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - PDGCode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BreitWigner",1122,G__PndJRGenCint_597_0_16, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - m0 d - 'Double_t' 0 - m "
"d - 'Double_t' 0 - Gamma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SampleMass",1014,G__PndJRGenCint_597_0_17, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - PDGCode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SampleLifetime",1425,G__PndJRGenCint_597_0_18, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "U 'TParticle' - 0 - mother", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Stable",603,G__PndJRGenCint_597_0_19, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - PDGCode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PoleWidth",912,G__PndJRGenCint_597_0_20, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - PDGCode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PCM",224,G__PndJRGenCint_597_0_21, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - Ecm d - 'Double_t' 0 - m1 "
"d - 'Double_t' 0 - m2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DefinePartialWaves",1822,G__PndJRGenCint_597_0_22, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - PDGCode i - 'Int_t' 0 - DecayChannel "
"I - 'Int_t' 0 - array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PWWeight",783,G__PndJRGenCint_597_0_23, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 1, 0, 
"U 'TGenPhaseSpace' - 0 - event i - 'Int_t' 0 - PdgCode "
"i - 'Int_t' 0 - channel i - 'Int_t' 0 - index", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetStable",903,G__PndJRGenCint_597_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "l - 'Long_t' 0 - PdgCode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("doElastic",920,G__PndJRGenCint_597_0_25, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPolarization",1576,G__PndJRGenCint_597_0_26, 121, -1, -1, 0, 3, 1, 1, 0, 
"l - 'Long_t' 0 - PdgCode l - 'Long_t' 0 - channel "
"f - 'Float_t' 0 - Polarization", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDecayAsymmetry",1757,G__PndJRGenCint_597_0_27, 121, -1, -1, 0, 3, 1, 1, 0, 
"l - 'Long_t' 0 - PdgCode l - 'Long_t' 0 - channel "
"f - 'Float_t' 0 - Asymmetry", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PndJRGenCint_597_0_28, 85, G__get_linked_tagnum(&G__PndJRGenCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PndReaction::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PndJRGenCint_597_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PndReaction::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PndJRGenCint_597_0_30, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PndReaction::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PndJRGenCint_597_0_31, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PndReaction::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PndJRGenCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PndJRGenCint_597_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PndJRGenCint_597_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PndReaction::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PndJRGenCint_597_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PndReaction::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PndJRGenCint_597_0_38, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PndReaction::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PndJRGenCint_597_0_39, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PndReaction::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("PndReaction", 1111, G__PndJRGenCint_597_0_40, (int) ('i'), G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction), -1, 0, 1, 1, 1, 0, "u 'PndReaction' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PndReaction", 1237, G__PndJRGenCint_597_0_41, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PndJRGenCint_597_0_42, (int) ('u'), G__get_linked_tagnum(&G__PndJRGenCintLN_PndReaction), -1, 1, 1, 1, 1, 0, "u 'PndReaction' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPndJRGenCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPndJRGenCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPndJRGenCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PndJRGenCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TClonesArray = { "TClonesArray" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__PndJRGenCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TParticle = { "TParticle" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TDecayChannel = { "TDecayChannel" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_TGenPhaseSpace = { "TGenPhaseSpace" , 99 , -1 };
G__linked_taginfo G__PndJRGenCintLN_PndReaction = { "PndReaction" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePndJRGenCint() {
  G__PndJRGenCintLN_TClass.tagnum = -1 ;
  G__PndJRGenCintLN_TBuffer.tagnum = -1 ;
  G__PndJRGenCintLN_TMemberInspector.tagnum = -1 ;
  G__PndJRGenCintLN_TObject.tagnum = -1 ;
  G__PndJRGenCintLN_TString.tagnum = -1 ;
  G__PndJRGenCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PndJRGenCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PndJRGenCintLN_TClonesArray.tagnum = -1 ;
  G__PndJRGenCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PndJRGenCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PndJRGenCintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__PndJRGenCintLN_TH1D.tagnum = -1 ;
  G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__PndJRGenCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__PndJRGenCintLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__PndJRGenCintLN_TVector3.tagnum = -1 ;
  G__PndJRGenCintLN_TParticle.tagnum = -1 ;
  G__PndJRGenCintLN_TDecayChannel.tagnum = -1 ;
  G__PndJRGenCintLN_TGenPhaseSpace.tagnum = -1 ;
  G__PndJRGenCintLN_PndReaction.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePndJRGenCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TString);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TClonesArray);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TH1D);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TVector3);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TParticle);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TDecayChannel);
   G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_TGenPhaseSpace);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PndJRGenCintLN_PndReaction),sizeof(PndReaction),-1,61440,(char*)NULL,G__setup_memvarPndReaction,G__setup_memfuncPndReaction);
}
extern "C" void G__cpp_setupPndJRGenCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupPndJRGenCint()");
  G__set_cpp_environmentPndJRGenCint();
  G__cpp_setup_tagtablePndJRGenCint();

  G__cpp_setup_inheritancePndJRGenCint();

  G__cpp_setup_typetablePndJRGenCint();

  G__cpp_setup_memvarPndJRGenCint();

  G__cpp_setup_memfuncPndJRGenCint();
  G__cpp_setup_globalPndJRGenCint();
  G__cpp_setup_funcPndJRGenCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPndJRGenCint();
  return;
}
class G__cpp_setup_initPndJRGenCint {
  public:
    G__cpp_setup_initPndJRGenCint() { G__add_setup_func("PndJRGenCint",(G__incsetup)(&G__cpp_setupPndJRGenCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPndJRGenCint() { G__remove_setup_func("PndJRGenCint"); }
};
G__cpp_setup_initPndJRGenCint G__cpp_setup_initializerPndJRGenCint;

