/*
 * PndLmdLumiFitOptions.h
 *
 *  Created on: Jun 27, 2012
 *      Author: steve
 */

#ifndef PNDLMDLUMIFITOPTIONS_H_
#define PNDLMDLUMIFITOPTIONS_H_

#include "TObject.h"
#include "TString.h"
#include "TMath.h"

/**
 * \brief This class contains the various fit options which are independent of the fit model itself.
 *
 * The user can choose between
 * - ROOT or ROOFIT
 * - acceptance correction or not
 * - 1d or 2d fit
 * - smearing or not
 * - theta and phi fit range
 * - use t instead theta
 *
 * These fit options objects should be generated by the user in the following two ways:
 * - using the #PndLmdLumiFitOptions(int, double, double, double, double) constructor
 * while these objects are passed to the PndLmdData::Fit() method.
 * - using the #PndLmdLumiFitOptions(int) constructor, which can be useful when one is searching the fit results
 *  for more general fit options
 *
 */
class PndLmdLumiFitOptions: public TObject {
private:
	/** This set of bits specifies all binary fit options will be used (so on-off type options)
	 * bit 0: 0 = no resolution smearing, 1 = with resolution smearing
	 * bit 1: 0 = no acceptance corr, 1 = with acceptance corr
	 * bit 2: 0 = 1d fit, 1 = 2d fit
	 * bit 3: 0 = use theta-phi data and fit function, 1 = use t (momentum transfer) data and fit function
	 * bit 4: 0 = ROOT, 1 = ROOFIT
	 **/
	unsigned long binary_options;
	unsigned int free_parameters_code;

	int smearing_type;
	int acc_intpol_type;

	double theta_fit_range_low; /** Lower boundary of the fit for the theta variable */
	double theta_fit_range_high; /** Upper boundary of the fit for the theta variable */
	double phi_fit_range_low; /** Lower boundary of the fit for the phi variable. This will only be used if fit dimension equals 2. */
	double phi_fit_range_high; /** Upper boundary of the fit for the phi variable. This will only be used if fit dimension equals 2. */

	double t_fit_range_low; /** Lower boundary of the fit for the t variable (calculated automatically from the @see theta_fit_range_low) */
	double t_fit_range_high; /** Upper boundary of the fit for the t variable (calculated automatically from the @see theta_fit_range_high) */

	void initBinaryOptions(unsigned long bit_flag_options);

public:
	/**
	 * Constructor
	 * @param bit_flag_options is a integer number, which is represented a set of binary flags:
	 *  bit 0: resolution smearing
	 *  bit 1: acceptance correction
	 *  bit 2: fit dimension
	 *  bit 3: use t instead of theta
	 *  bit 4: fitter type
	 *  The highest number can therefore be 31 and the lowest 0 (higher numbers than 31 are regarded as 31).
	 *
	 *  @param smearing_type is a
	 */
	PndLmdLumiFitOptions(unsigned long bit_flag_options, int smearing_type_,
			int acc_intpol_type_);

	/**
	 * Constructor
	 * @param bit_flag_options is a number in which each digit represents a binary flag @see PndLmdLumiFitOptions(int)
	 * @param free_parameters_code_ is a bitcode specifying which parameter is free in the fit procedure
	 * @param smearing_type_ specifies which model is used for the smearing (0 = gaussian, 1 = double gaussian)
	 * @param acc_intpol_type_ specifies the interpolation type of the acceptance (D
	 * @param plab
	 * @param theta_fit_range_low_ used as the new lower fit range for theta
	 * @param theta_fit_range_high_ used as the new upper fit range for theta
	 * @param phi_fit_range_low_ used as the new lower fit range for phi
	 * @param phi_fit_range_high_ used as the new upper fit range for phi
	 */
	PndLmdLumiFitOptions(unsigned long bit_flag_options,
			unsigned int free_parameters_code_, int smearing_type_,
			int acc_intpol_type_, double plab, double theta_fit_range_low_,
			double theta_fit_range_high_, double phi_fit_range_low_ = -TMath::Pi(),
			double phi_fit_range_high_ = TMath::Pi());

	/**
	 * Constructor
	 * empty constructor only required by ROOT IO
	 */
	PndLmdLumiFitOptions();

	/**
	 * Get method for the smearing function type
	 * @returns smearing model type (atm: 0 = single gaussian, 1 = double gaussian)
	 */
	int getSmearingModelType() const;
	/**
	 * Get method for the smearing function name
	 * @returns smearing model name (i.e: "single gaussian" or "double gaussian")
	 */
	std::string getSmearingModelName() const;

	/**
	 * Get method for the fit dimension (1D or 2D)
	 * @returns fit dimension (0 = 1d fit, 1 = 2d fit)
	 */
	bool getFitDimension() const;
	/**
	 * Get method for the fitter type (ROOT or ROOFIT)
	 * @returns fitter type (0 = ROOT, 1 = ROOFIT)
	 */
	bool getFitterType() const;
	/**
	 * Checks if resolution smearing is on.
	 * @returns true if smearing is on, false if off
	 */
	bool isSmearingOn() const;
	/**
	 * Checks if acceptance correction is on
	 * @returns true if acceptance correction will be used, false otherwise
	 */
	bool isAcceptanceCorrOn() const;
	/**
	 * Checks if raw fit mode will be used
	 * @returns true if t spectrum and function will be used instead of theta, false otherwise
	 */
	bool isFitRaw() const;

	int getAcceptanceInterpolationType() const;
	/**
	 * Get method for the binary fit options
	 * @returns integer format of the binary fit options
	 */
	unsigned long getBinaryOptions() const;
	/**
	 * @returns the code for which parameter is free in the fit
	 */
	unsigned int getFreeParametersCode() const;
	/**
	 * @returns the lower fit boundary for the theta variable
	 */
	double getThetaFitRangeLow() const;
	/**
	 * @returns the upper fit boundary for the theta variable
	 */
	double getThetaFitRangeHigh() const;
	/**
	 * @returns the lower fit boundary for the phi variable
	 */
	double getPhiFitRangeLow() const;
	/**
	 * @returns the upper fit boundary for the phi variable
	 */
	double getPhiFitRangeHigh() const;

	/**
	 * @returns the lower fit boundary for the t variable
	 */
	double getTFitRangeLow() const;
	/**
	 * @returns the upper fit boundary for the t variable
	 */
	double getTFitRangeHigh() const;

	void setAcceptanceInterpolationType(int acc_intpol_type_);

	void setSmearingModelType(int smearing_type_);
	/**
	 * Setter method for switching between theta and t
	 * @param use_raw_ specifies if raw (momentum transfer) should be used
	 */
	void setFitAsRaw(bool use_raw_);
	/**
	 * Setter method for the fit dimension (1D or 2D)
	 * @param fit_dimension_ is the new fit dimension that will be used
	 */
	void setFitDimension(bool fit_dimension_);
	/**
	 * Setter method for the fitter type (ROOT or ROOFIT)
	 * @param fitter_type_ is the new fit type that will be used
	 */
	void setFitterType(bool fitter_type_);
	/**
	 * Setter method for the smearing mode (0 disabled, 1 enabled)
	 * @param with_smearing_ is the new fit dimension that will be used
	 */
	void setSmearingMode(bool with_smearing_);
	/**
	 * Setter method for the acceptance correction mode (0 disabled, 1 enabled)
	 * @param with_acceptance_corr_ is the new fit dimension that will be used
	 */
	void setAcceptanceCorrMode(bool with_acceptance_corr_);
	/**
	 * This function will set the #free_parameters_code field. This code decides
	 * which parameters will be set free in the fit later on.
	 * @param free_parameters_code_ is new value of #free_parameters_code
	 */
	void setFreeParametersOfModel(unsigned int free_parameters_code_);

	/**
	 * Comparison operator. Will return true only if all fit options are equal in value.
	 */
	bool operator==(const PndLmdLumiFitOptions &fit_options) const;
	/**
	 * Inverse comparison operator @see operator==()
	 */
	bool operator!=(const PndLmdLumiFitOptions &fit_options) const;
	/**
	 * Output stream operator for printing out fit options for information.
	 */
	friend std::ostream& operator<<(std::ostream& os,
			const PndLmdLumiFitOptions& fit_options);

	TString makeName() const;

ClassDef(PndLmdLumiFitOptions,1)
};

#endif /* PNDLMDLUMIFITOPTIONS_H_ */
