#!/bin/bash 
################################################################
## script for test cuts from rec as influence on determination of luminosity
## BOX data and DPM data should be generated before
## 26/03/2014 1st version
## A.Karavdina
################################################################
echo Enter momentum from "1.5, 4.06, 8.9, 11.91, 15 [GeV/c]":
read mom
echo "Beam mometum is: $mom!"
cd ${VMCWORKDIR}/macro/lmd/
pbeam=$mom
momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`
pathBOX0=/panda/myResults/BOXoutpitMarch2014_pointBeam/mom_${momStr}/
pathDPM0=/panda/myResults/DPMoutputMarch2014_pointBeam/mom_${momStr}/
pathBOX=/panda/myResults/BOXoutput_pointBeam_newXYCut/mom_${momStr}/
pathDPM=/panda/myResults/DPMoutput_pointBeam_newXYCut/mom_${momStr}/
pathBOX2=/panda/myResults/BOXoutput_pointBeam_newXYCut_MCut/mom_${momStr}/
pathDPM2=/panda/myResults/DPMoutput_pointBeam_newXYCut_MCut/mom_${momStr}/
#thcutVal=1.0

### preparation for the luminosity fit
cd ${VMCWORKDIR}/buildPanda/bin
#./createLumiFitData -t 0 -p ${pathDPM} -g 0.102459016393442626 ### 15 GeV/c, -g= 1./sigma_tot_el

#for thcutVal in 5000000 0.07 0.14 0.21 0.28 0.35 0.42 0.49 0.56 0.63 0.70
#for thcutVal in 5000000
for thcutVal in -100
#for thcutVal in 0.21
do 
    thcutValStr=`echo $thcutVal | sed -e '{ s/\./_/g; }'`
    ./createLumiFitData -n 20000000  -m 15 -t a -p ${pathDPM} -c 9.7603140  -a ${thcutVal}  #&> ${pathDPM}/log_dpm_data_create_${thcutValStr} #data 15 GeV 
    ./createLumiFitData -n 20000000 -m 15 -t er -p ${pathBOX} -a ${thcutVal}  #&> ${pathDPM}/log_acc_res_data_create_${thcutValStr} #acc & res
    ./determineResolution -d ${pathBOX}  #&> ${pathDPM}/log_determineResolution_${thcutValStr}
    ./plotResolutionParametrization -d  ${pathBOX} -l 0
    ### and now let's fit the luminosity
    ./runLumiFit -d ${pathDPM} -a ${pathBOX} &> ${pathDPM}/log_runLumiFit_${thcutValStr}
    ./plotLumiFitResults ${pathDPM}
   
    mv fitresults_overview.pdf ${pathDPM}/fitresults_overview_Thcut_${thcutValStr}.pdf
    mv lumifit_reco.pdf ${pathDPM}/lumifit_reco_Thcut_${thcutValStr}.pdf
    mv resolution.pdf ${pathDPM}/resolution_Thcut_${thcutValStr}.pdf
    mv ${pathBOX}/resolution_params_1.root ${pathDPM}/resolution_params_1_${thcutValStr}.root
    mv ${pathBOX}/resolution_params_0.root ${pathDPM}/resolution_params_0_${thcutValStr}.root
    mv ${pathBOX}/lmd_acc_data.root ${pathDPM}/lmd_acc_data_${thcutValStr}.root
    mv ${pathDPM}/lmd_data.root ${pathDPM}/lmd_data_${thcutValStr}.root

    ./createLumiFitData -n 20000000  -m 15 -t a -p ${pathDPM2} -c 9.7603140  -a ${thcutVal} # &> ${pathDPM}\log_dpm_data_create_${thcutValStr} #data 15 GeV 
    ./createLumiFitData -n 20000000 -m 15 -t er -p ${pathBOX2} -a ${thcutVal} # &> ${pathDPM}\log_acc_res_data_create_${thcutValStr} #acc & res
    ./determineResolution -d ${pathBOX2} #&> ${pathDPM}\log_determineResolution_${thcutValStr}
    ./plotResolutionParametrization -d  ${pathBOX2} -l 0
    ### and now let's fit the luminosity
    ./runLumiFit -d ${pathDPM2} -a ${pathBOX2} &> ${pathDPM2}/log_runLumiFit_${thcutValStr}
    ./plotLumiFitResults ${pathDPM2}
    thcutValStr=`echo $thcutVal | sed -e '{ s/\./_/g; }'`
    mv fitresults_overview.pdf ${pathDPM2}/fitresults_overview_Thcut_${thcutValStr}.pdf
    mv lumifit_reco.pdf ${pathDPM2}/lumifit_reco_Thcut_${thcutValStr}.pdf
    mv resolution.pdf ${pathDPM2}/resolution_Thcut_${thcutValStr}.pdf
    mv ${pathBOX2}/resolution_params_1.root ${pathDPM2}/resolution_params_1_${thcutValStr}.root
    mv ${pathBOX2}/resolution_params_0.root ${pathDPM2}/resolution_params_0_${thcutValStr}.root
    mv ${pathBOX2}/lmd_acc_data.root ${pathDPM2}/lmd_acc_data_${thcutValStr}.root
    mv ${pathDPM2}/lmd_data.root ${pathDPM2}/lmd_data_${thcutValStr}.root

    ./createLumiFitData -n 20000000  -m 15 -t a -p ${pathDPM0} -c 9.7603140  -a ${thcutVal} # &> ${pathDPM}/log_dpm_data_create_${thcutValStr} #data 15 GeV 
    ./createLumiFitData -n 20000000 -m 15 -t er -p ${pathBOX0} -a ${thcutVal} # &> ${pathDPM}/log_acc_res_data_create_${thcutValStr} #acc & res
    ./determineResolution -d ${pathBOX0} #&> ${pathDPM}\log_determineResolution_${thcutValStr}
    ./plotResolutionParametrization -d  ${pathBOX0} -l 0
    ### and now let's fit the luminosity
    ./runLumiFit -d ${pathDPM0} -a ${pathBOX0} &> ${pathDPM0}\log_runLumiFit_${thcutValStr}
    ./plotLumiFitResults ${pathDPM0}
    thcutValStr=`echo $thcutVal | sed -e '{ s/\./_/g; }'`
    mv fitresults_overview.pdf ${pathDPM0}/fitresults_overview_Thcut_${thcutValStr}.pdf
    mv lumifit_reco.pdf ${pathDPM0}/lumifit_reco_Thcut_${thcutValStr}.pdf
    mv resolution.pdf ${pathDPM0}/resolution_Thcut_${thcutValStr}.pdf
    mv ${pathBOX0}/resolution_params_1.root ${pathDPM0}/resolution_params_1_${thcutValStr}.root
    mv ${pathBOX0}/resolution_params_0.root ${pathDPM0}/resolution_params_0_${thcutValStr}.root
    mv ${pathBOX0}/lmd_acc_data.root ${pathDPM0}/lmd_acc_data_${thcutValStr}.root
    mv ${pathDPM0}/lmd_data.root ${pathDPM0}/lmd_data_${thcutValStr}.root
done 
