#$ -wd /tmp 
#$ -j y
#$ -V

cd $TMPDIR

. $FAIRLIBDIR"/../config.sh"

hera=$VMCWORKDIR"/tutorials/analysis"
_target=$hera"/data/"

command=$1
command=${command/SGE_TASK_ID/$SGE_TASK_ID}

echo $PWD
echo root -l -b -q \'$command\'
root -l -b -q $command

# Move the data to the persistent storage
cp -v $TMPDIR/*_ana.root $_target
rm $TMPDIR/*_ana.root
 
# Evacuate the log-file
cp -v $SGE_STDOUT_PATH $_target/$JOB_ID.log
