export Linux_Flavour_="Scientific Linux release 6.0 (Carbon)"
export System_="x86_64"
source /home/karavdin/pandaRoot12/build/check_system.sh                               
if [ "$same_system" == "1" ]; then 
  export SIMPATH="/cluster/gsi/fairsoft/gcc/fairsoft_sep12"
  export ROOTSYS="/cluster/gsi/fairsoft/gcc/fairsoft_sep12"
  if (true); then
    export GEANT4_LIBRARY_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib"
    export GEANT4_INCLUDE_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/include/Geant4:/cluster/gsi/fairsoft/gcc/fairsoft_sep12/transport/geant4/source/interfaces/common/include:/cluster/gsi/fairsoft/gcc/fairsoft_sep12/transport/geant4/physics_lists/hadronic/Packaging/include:/cluster/gsi/fairsoft/gcc/fairsoft_sep12/transport/geant4/physics_lists/hadronic/QGSP/include"
    export GEANT4VMC_INCLUDE_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/include/geant4vmc"
    export GEANT4VMC_LIBRARY_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib"
    export GEANT4VMC_MACRO_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/geant4_vmc/macro"
    export CLHEP_INCLUDE_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/include/Geant4"
    export CLHEP_LIBRARY_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib"
    export CLHEP_BASE_DIR=""
    export PLUTO_LIBRARY_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib"
    export PLUTO_INCLUDE_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/include/pluto"
    export PYTHIA6_LIBRARY_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib"
    export G3SYS="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/geant3"
    export GEANT3_INCLUDE_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/include/TGeant3"
    export GEANT3_LIBRARY_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib"
    export GEANT3_LIBRARIES="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib/libgeant321.so"
    export USE_VGM="1"
    export PYTHIA8DATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/generators/pythia8/xmldoc"
    export CLASSPATH=""
    export G4LEDATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/G4EMLOW6.23"
    export G4LEVELGAMMADATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/PhotonEvaporation2.2"
    export G4NeutronHPCrossSections="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/G4NDL4.0"
    export G4NEUTRONHPDATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/G4NDL4.0"
    export G4NEUTRONXSDATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/G4NEUTRONXS1.1"
    export G4PIIDATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/G4PII1.3"
    export G4RADIOACTIVEDATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/RadioactiveDecay3.4"
    export G4REALSURFACEDATA="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/share/Geant4/data/RealSurface1.0"
  fi
  export ROOT_LIBRARY_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib/root"
  export ROOT_LIBRARIES="-L/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib/root -lGui -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic"
  export ROOT_INCLUDE_DIR="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/include/root"
  export VMCWORKDIR="/home/karavdin/pandaRoot12"
  export FAIRLIBDIR="/home/karavdin/pandaRoot12/build/lib"
  export DYLD_LIBRARY_PATH=""
  export LD_LIBRARY_PATH="/home/karavdin/pandaRoot12/build/lib:/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib/root:/cluster/gsi/fairsoft/gcc/fairsoft_sep12/lib"
  export PATH="/cluster/gsi/fairsoft/gcc/fairsoft_sep12/bin:/usr/mpi/gcc/openmpi-1.4.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/maui/bin/:/home/karavdin/bin"
fi
