export Linux_Flavour_="Fedora release 12 (Constantine)"
export System_="i686"
. /local/data/fair/fairsoft10/pandaroot/build/check_system.sh
 if [ "$same_system" == "1" ]; then
export SIMPATH="/local/data/fair/fairsoft10/"
export ROOTSYS="/local/data/fair/fairsoft10/tools/root"
export GEANT4_LIBRARY_DIR="/local/data/fair/fairsoft10/transport/geant4/lib/Linux-g++"
export GEANT4_INCLUDE_DIR="/local/data/fair/fairsoft10//transport/geant4/include:/local/data/fair/fairsoft10//transport/geant4/source/interfaces/common/include:/local/data/fair/fairsoft10//transport/geant4/physics_lists/hadronic/Packaging/include:/local/data/fair/fairsoft10//transport/geant4/physics_lists/hadronic/QGSP/include"
export GEANT4VMC_INCLUDE_DIR="/local/data/fair/fairsoft10//transport/geant4_vmc/source/global/include:/local/data/fair/fairsoft10//transport/geant4_vmc/source/geometry/include:/local/data/fair/fairsoft10//transport/geant4_vmc/source/digits+hits/include:/local/data/fair/fairsoft10//transport/geant4_vmc/source/physics/include:/local/data/fair/fairsoft10//transport/geant4_vmc/source/event/include:/local/data/fair/fairsoft10//transport/geant4_vmc/source/run/include:/local/data/fair/fairsoft10//transport/geant4_vmc/source/interfaces/include:/local/data/fair/fairsoft10//transport/geant4_vmc/source/visualization/include:/local/data/fair/fairsoft10//transport/geant4_vmc/include:/local/data/fair/fairsoft10//transport/vgm/packages/BaseVGM/include:/local/data/fair/fairsoft10//transport/vgm/packages/ClhepVGM/include:/local/data/fair/fairsoft10//transport/vgm/packages/Geant4GM/include:/local/data/fair/fairsoft10//transport/vgm/packages/RootGM/include:/local/data/fair/fairsoft10//transport/vgm/packages/VGM/include:/local/data/fair/fairsoft10//transport/vgm/packages/XmlVGM/include"
export GEANT4VMC_LIBRARY_DIR="/local/data/fair/fairsoft10/transport/geant4_vmc/lib/tgt_linux"
export GEANT4VMC_MACRO_DIR="/local/data/fair/fairsoft10//transport/geant4_vmc/examples/macro/"
export CLHEP_INCLUDE_DIR="/local/data/fair/fairsoft10/cern/clhep/include"
export CLHEP_LIBRARY_DIR="/local/data/fair/fairsoft10/cern/clhep/lib"
export PLUTO_LIBRARY_DIR="/local/data/fair/fairsoft10/generators/lib"
export PLUTO_INCLUDE_DIR="/local/data/fair/fairsoft10/generators/pluto/src"
export PYTHIA6_LIBRARY_DIR="/local/data/fair/fairsoft10/generators/lib"
export G3SYS="/local/data/fair/fairsoft10/transport/geant3"
export GEANT3_INCLUDE_DIR="/local/data/fair/fairsoft10/transport/geant3/TGeant3"
export GEANT3_LIBRARY_DIR="/local/data/fair/fairsoft10/transport/geant3/lib/tgt_linux"
export GEANT3_LIBRARIES="/local/data/fair/fairsoft10/transport/geant3/lib/tgt_linux/libgeant321.so"
export ROOT_LIBRARY_DIR="/local/data/fair/fairsoft10/tools/root/lib"
export ROOT_LIBRARIES="-L/local/data/fair/fairsoft10/tools/root/lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lGui -pthread -lm -ldl -rdynamic"
export ROOT_INCLUDE_DIR="/local/data/fair/fairsoft10/tools/root/include"
export VMCWORKDIR="/local/data/fair/fairsoft10/pandaroot/trunk"
export FAIRLIBDIR="/local/data/fair/fairsoft10/pandaroot/build/lib"
export LD_LIBRARY_PATH="/local/data/fair/fairsoft10/pandaroot/build/lib:/local/data/fair/fairsoft10/pandaroot/build/lib:/local/data/fair/fairsoft10/tools/root/lib:/local/data/fair/fairsoft10/generators/lib:/local/data/fair/fairsoft10/generators/lib:/local/data/fair/fairsoft10/transport/geant3/lib/tgt_linux:/local/data/fair/fairsoft10/transport/geant4/lib/Linux-g++:/local/data/fair/fairsoft10/transport/geant4_vmc/lib/tgt_linux:/local/data/fair/fairsoft10/transport/vgm/lib:/local/data/fair/fairsoft10/cern/clhep/lib"
export USE_VGM="1"
export PATH="/local/data/fair/fairsoft10/tools/root/bin:/home/karavdin/root/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/karavdin/bin"
. /local/data/fair/fairsoft10/transport/geant4/env.sh
fi
