#!/bin/bash
time root -l -b -q 'runLumi0SimBox.C(10000)'
time root -l -b -q 'runLumi1Digi.C(10000)'
time root -l -b -q 'runLumi2Reco.C(10000)'
#time root -l -b -q 'HitsInfo.C(100)'
time root -l -b -q 'runLumi3Finder.C(10000)'
time root -l -b -q 'runLumi4Fitter.C(10000)'
#time root -l -b -q 'TracksParamsInfo.C(10000)'
time root -l -b -q 'runLumi5Geane.C(10000)'
time root -l -b -q 'MyTestLumiMultiEvn.C(10000)'
#root -l -b -q 'MyTestLumi.C(2)'
exit
