#!/bin/bash


#numer of events used for resolution study
SIMEVENTS=100000
ARRAY=(100000)
# get number of elements in the array
ELEMENTS=${#ARRAY[@]}

#Declare array with elements for misalignment scale
ARRAYD=(0 20 30 50 70 100 150 200 250 300 350 400 450 500) #mum
#ARRAYD=(100) #mum
ELEMENTSD=${#ARRAYD[@]}
#ARRAYA=(1 3 5 7 10 20) # 1e-3 rad
ARRAYA=(0) # 1e-3 rad
# get number of elements in the array
ELEMENTSA=${#ARRAYA[@]}
#CRFILE=(0 1 1 1 1 1 1 1) #mum
# echo each element in array 
# for loop
 for (( j=0;j<$ELEMENTSD;j++)); do
     for (( ia=0;ia<$ELEMENTSA;ia++)); do
	 for (( i=0;i<$ELEMENTS;i++)); do
	 T="$(date)"
	echo ${T} ": Now we'll add info about test with "${ARRAY[${i}]} "events for misalignment ~ "${ARRAYD[${j}]} "mum and" ${ARRAYA[${ia}]} "*10e-3 rad"
# #----------------------------------------------------------------------

	pathname=/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign/results/misalign_${ARRAYD[${j}]}mum_${ARRAYA[${ia}]}_10e-3radDOF111111_${ARRAY[${i}]}_events
#	    pathname=/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign/results/misalign_${ARRAYD[${j}]}mum_DOF111000_${ARRAY[${i}]}_events
#	pathname=/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign/results/misalign${ARRAYA[${ia}]}_10e-3radDOF000111_${ARRAY[${i}]}_events
	resfile=/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign/results/Sens.root
	time root -l -b -q GenAlignEffect.C\(\"${pathname}/\",${ARRAYD[${j}]},${j},${ELEMENTSD},\"${resfile}\"\)
# # #---------------------------------------------------------------------- 
	 done
     done
 done
echo "results saved in " ${pathname}
exit
