#!/bin/bash      
time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'create_misalignment_lumi.C(0,0)'
cp lumi.misalign.par lumi.misalign_0_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_0_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/


time root -l -b -q 'create_misalignment_lumi.C(0.0005,0)'
cp lumi.misalign.par lumi.misalign_5_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_5_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/

time root -l -b -q 'create_misalignment_lumi.C(0.0010,0)'
cp lumi.misalign.par lumi.misalign_10_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_10_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/

time root -l -b -q 'create_misalignment_lumi.C(0.0020,0)'
cp lumi.misalign.par lumi.misalign_20_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_20_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/

time root -l -b -q 'create_misalignment_lumi.C(0.0050,0)'
cp lumi.misalign.par lumi.misalign_50_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_50_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/

time root -l -b -q 'create_misalignment_lumi.C(0.01,0)'
cp lumi.misalign.par lumi.misalign_100_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_100_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/

time root -l -b -q 'create_misalignment_lumi.C(0.02,0)'
cp lumi.misalign.par lumi.misalign_200_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_200_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/

time root -l -b -q 'create_misalignment_lumi.C(0.05,0)'
cp lumi.misalign.par lumi.misalign_500_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_500_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/

time root -l -b -q 'create_misalignment_lumi.C(0.1,0)'
cp lumi.misalign.par lumi.misalign_1000_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root Lumi_out_MC_and_REC_trks_matches_with_IDs_1000_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/


#rm TracksHits.txt
#time root -l -b -q 'AlignmentStudies.C(5000,0,"tmpOutputAlign")' >> TracksHits.txt

exit
