#!/bin/bash 
################################################################
## script for running sim&rec for trk reconstruction performance
## [with pixels sensors set-up!]
## 05/10/2012
## A.Karavdina
################################################################
path=${VMCWORKDIR}/macro/lmd/tmpOutnewDesign
mkdir ${path}
#mergedHits=true
numEv=100000
#pbeam=11.91

#numEv=100
for pbeam in 15 1.5 4.06 8.9 11.91
#for pbeam in 15 8.9 1.5 
do
    for numTrks in 15 10 1 2 3 4 5
     # for numTrks in 3
    do
    mergedHits=true
    addMS=true
    root -l -b -q runLumiPixel0SimBox.C\(${numEv},${pbeam},"\"${path}\"",0,-2212,${numTrks}\)
    root -l -b -q runLumiPixel1Digi.C\(${numEv},0,"\"${path}\""\)
    root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)
    root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\)

    ##CA & Minuit
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\) >> ${path}/logPixel_CA_${numTrks}trks_mergedHits
    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1 -mh 1 -v 0 -path ${path}
    ./hits_study -s 0 -n ${numEv} -path ${path} -out ${path}/ResidualsHist_${numTrks}_${pbeam}_mergedHits_${mergedHits}_addMS_${addMS}.root -st 1 -mh ${mergedHits} -v 1

   cd ${VMCWORKDIR}/macro/lmd
   mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit_${pbeam}.root

    # ##Trk-Follow & Minuit
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"Follow\"",true,${mergedHits}\) >> ${path}/logPixel_Follow_${numTrks}trks_mergedHits
    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1  -mh 1 -v 0 -path ${path}
    cd ${VMCWORKDIR}/macro/lmd
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit_${pbeam}.root

    addMS=false
    root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)
    ## CA & Kalman
    root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\)
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\)
    time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\)
    time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1  -mh 1 -v 0 -path ${path}
    ./hits_study -s 0 -n ${numEv} -path ${path} -out ${path}/ResidualsHist_${numTrks}_${pbeam}_mergedHits_${mergedHits}_addMS_${addMS}.root -st 1 -mh ${mergedHits} -v 1
    cd ${VMCWORKDIR}/macro/lmd
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_KalmanFillter_${pbeam}.root

    ##Trk-Follow & Kalman
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"Follow\"",true,${mergedHits}\)
    time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\)
    time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1  -mh 1 -v 0 -path ${path}
    cd ${VMCWORKDIR}/macro/lmd
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_KalmanFillter_${pbeam}.root

    # ##don't merge hits
    mergedHits=false
  
    addMS=true
    root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)
    ##CA & Minuit
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\)  >> ${path}/logPixel_CA_${numTrks}trks_singleHits
    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1 -mh 0 -v 0 -path ${path}
    ./hits_study -s 0 -n ${numEv} -path ${path} -out ${path}/ResidualsHist_${numTrks}_${pbeam}_mergedHits_${mergedHits}_addMS_${addMS}.root -st 1 -mh ${mergedHits} -v 1

    cd ${VMCWORKDIR}/macro/lmd
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_MinuitFit_${pbeam}.root

    addMS=false
    root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)
    ## CA & Kalman
    root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits}\)
    time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\)
    time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)
    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1 -mh 0 -v 0 -path ${path}
    cd ${VMCWORKDIR}/macro/lmd
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_mergedHits_${mergedHits}_addMS_${addMS}_KalmanFillter_${pbeam}.root
done
done
exit
