#!/bin/bash      
path=${VMCWORKDIR}/macro/lmd/tmpOutoldDesign
mkdir ${path}
#numTrks=1
numEv=100000
#take into account multiple scattering in hit errors calculation

#for pbeam in 15 1.5 11.91 8.9 4.06
for pbeam in 15
do 
#    for numTrks in 15 10 5 4 3 2 1
    for numTrks in 1
    do
time root -l -b -q runLumi0SimBox.C\(${numEv},${pbeam},"\"${path}\"",0,-2212,${numTrks}\)
time root -l -b -q runLumi1Digi.C\(${numEv},0,"\"${path}\""\)

addMS=true
time root -l -b -q runLumi2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\) >> ${path}/logStrip_HitRec_${numTrks}trks_${pbeam}GeV

time root -l -b -q runLumi3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true\) >> ${path}/logStrip_CA_${numTrks}trks_${pbeam}GeV
time root -l -b -q runLumi4Fitter.C\(${numEv},0,"\"${path}\""\) >> ${path}/logStrip_MinuitFit_${numTrks}trks_${pbeam}GeV
time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\""\) >> ${path}/logStrip_GEANE_${numTrks}trks_${pbeam}GeV
cd ${VMCWORKDIR}/build/bin
./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 0 -v 0 -path ${path}  >> logSTRIP_CA_Minuit_mc_rec_match

cd ${VMCWORKDIR}/macro/lmd/
mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_MinuitFit_${pbeam}_GEANT4.root
rm ${path}/Lumi_Track_0.root
rm ${path}/Lumi_Geane_0.root

time root -l -b -q runLumi3Finder.C\(${numEv},0,"\"${path}\"",0,"\"Follow\"",true\) >> ${path}/logStrip_Follow_${numTrks}trks_${pbeam}GeV
time root -l -b -q runLumi4Fitter.C\(${numEv},0,"\"${path}\""\)
time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\""\)
cd ${VMCWORKDIR}/build/bin
./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 0 -v 0 -path ${path}  >> logSTRIP_Follow_Minuit_mc_rec_match

cd ${VMCWORKDIR}/macro/lmd/
mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_${numTrks}trks_MinuitFit_${pbeam}.root
rm ${path}/Lumi_Track_0.root
rm ${path}/Lumi_Geane_0.root

addMS=false
time root -l -b -q runLumi2Reco.C\(${numEv},0,"\"${path}\"",0,${addMS}\)

time root -l -b -q runLumi3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true\)
time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,0\) >> ${path}/logStrip_KalmanFit_${numTrks}trks_${pbeam}GeV
time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\""\)
 
cd ${VMCWORKDIR}/build/bin
./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 0 -v 0 -path ${path}
cd ${VMCWORKDIR}/macro/lmd
mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_KalmanFillter_${pbeam}_GEANT4.root

time root -l -b -q runLumi3Finder.C\(${numEv},0,"\"${path}\"",0,"\"Follow\"",true\)
time root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,0\)
time root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\""\)
 
cd ${VMCWORKDIR}/build/bin
./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 0 -v 0 -path ${path}
cd ${VMCWORKDIR}/macro/lmd
mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_${numTrks}trks_KalmanFillter_${pbeam}.root

done
done
exit
