#!/bin/bash 
################################################################
## script for running sim&rec for trk reconstruction performance
## [with pixels sensors set-up!]
## 05/10/2012
## A.Karavdina
################################################################
path=${VMCWORKDIR}/macro/lmd/tmpOutnewDesign
mkdir ${path}
numTrks=1
#for numTrks in 1 2 3 4 5 10 15
#for numTrks in 1
#for pbeam in 1.5 4.06 8.9 11.91 15
for pbeam in 15
do
    root -l -b -q runLumiPixel0SimBox.C\(10000,${pbeam},"\"${path}\"",0,-2212,${numTrks}\)
    root -l -b -q runLumiPixel1Digi.C\(10000,0,"\"${path}\""\)
    root -l -b -q runLumiPixel2Reco.C\(10000,0,"\"${path}\""\)
    root -l -b -q runLumiPixel2bHitMerge.C\(10000,0,"\"${path}\""\)
    root -l -b -q runLumiPixel3Finder.C\(10000,0,"\"${path}\"",0,"\"CA\"",true\) >> logNEW_CA_${numTrks}trks
    root -l -b -q runLumiPixel4Fitter.C\(10000,0,"\"${path}\""\)
    root -l -b -q runLumi5Geane.C\(10000,${pbeam},0,"\"${path}\"",0,1\)
 #   root -l -b -q runLumi7QA.C\(100000,0,"\"${path}\""\)
    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n 10000 -t ${numTrks} -mom ${pbeam} -npx 1 -v 0 -path ${path}
   # ./hits_align_pixel -s 0 -n 1000 -path ${path} -out ${path}/TrackForAlign.txt -outhist ${path}/ResidualsHist_${pbeam}.root -v 0

 #    cd ${VMCWORKDIR}/macro/lmd
 #    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_CA_${numTrks}trks_${pbeam}.root

 #    root -l -b -q runLumiPixel3Finder.C\(10000,0,"\"${path}\"",0,"\"Follow\""\) >> logNEW_Follow_${numTrks}trks
 #    root -l -b -q runLumiPixel4Fitter.C\(10000,0,"\"${path}\""\)
 #    root -l -b -q runLumi5Geane.C\(10000,${pbeam},0,"\"${path}\"",0,1\)
    
 #    cd ${VMCWORKDIR}/build/bin
 #    ./rec_mc_match -s 0 -n 10000 -t ${numTrks} -mom ${pbeam} -npx 1 -v 0 -path ${path}
 #    cd ${VMCWORKDIR}/macro/lmd
 #    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_Follow_${numTrks}trks_${pbeam}.root
    done

# mkdir /myResults/LUMI_Trk/pixelDesign/10000events
# mv tmpOutnewDesign/Lumi_out_MC_and_REC_trks_matches_with_IDs0_* /myResults/LUMI_Trk/pixelDesign/10000events/.
# mv logNEW* /myResults/LUMI_Trk/pixelDesign/10000events/.
