#!/bin/bash 
################################################################
## script for running sim&rec for LMD with BOX or DPM generator
## [with pixels sensors set-up!]
## 13/11/2012 1st version
## 06/09/2013 updated version
## 23/03/2014 more or less final version
## A.Karavdina
################################################################
echo Enter momentum from "1.5, 4.06, 8.9, 11.91, 15 [GeV/c]":
read mom
echo "Beam mometum is: $mom!"
cd ${VMCWORKDIR}/macro/lmd/
pbeam=$mom
momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`

#number of trks per event
numTrks=1
#number of events
numEv=25000

path=${VMCWORKDIR}/macro/lmd/DPMelinel_${numEv}ev/mom_${momStr}/
mkdir -p ${path}
##############
# set flags

## Write all MC info in TrkQA array
#WrAllMC=true
##############


# # # #simulation with DPM
#   modeDPM=0 #inel
    modeDPM=1 #el+inel
 #    modeDPM=2 #el
     root -l -b -q runLumiPixel0SimDPMDirect.C\(${numEv},0,${pbeam},"\"${path}\"",0,35162,$modeDPM,0.12\)

# #digi
     root -l -b -q runLumiPixel1Digi.C\(${numEv},0,"\"${path}\"",0\) 

# # signal/background digi
     root -l -b -q runLumiPixel8DigiQA.C\(${numEv},0,"\"${path}\"",0\)
     ${VMCWORKDIR}/buildPanda/bin/./hits_pattern $path $momStr
