#!/bin/bash
PANDAROOT=/data/FAIRsorf/pandaroot/trunk
PANDAROOTmy=/data/FAIRsorf/pandaroot/karavdina
# #----------------------------------------------------------------------
mkdir ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP
mkdir ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results
#rm /home/akaravdina/lmdMacro/tmpOutputAlign/*

##Full sim & rec
time root -l -b -q 'runLumi0SimBox.C(1000,11.91,"tmpOutputAlignTMP")'
time root -l -b -q 'runLumi1Digi.C(1000,0,"tmpOutputAlignTMP")'
time root -l -b -q 'create_misalignment_lumi.C(100.,0.)'
time root -l -b -q 'runLumi2Reco.C(1000,0,"tmpOutputAlignTMP")' >> REC_TESTmisalign100mkmDOF111000.log
time root -l -b -q 'runLumi3Finder.C(1000,0,"tmpOutputAlignTMP", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(1000,0,"tmpOutputAlignTMP")'
time root -l -b -q 'runLumi5Geane.C(1000,11.91,0,"tmpOutputAlignTMP")'

cd ${PANDAROOT}/build/bin
##obtain information about resolution before alignment
./rec_mc_match -s 0 -n 1000 -mom 11.91 -path ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP

##obtain info about hits for alignment
./hits_align -s 0 -n 1000 -path ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP -out ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/TrackForAlign.txt -outhist ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/ResidualsHist.root -v 0

##do alignment
cd ${PANDAROOTmy}/myKnossos
rm logForRES
./knossos -i ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/TrackForAlign.txt -o ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/LumiAlignConst.txt -n 1000 -r 1 >> logForRES

#obtain results and write it in new *.par file
rm ${PANDAROOT}/macro/lmd/lumi.misalign_after.par
head -14 ${PANDAROOT}/macro/lmd/lumi.misalign.par >> ${PANDAROOT}/macro/lmd/lumi.misalign_after.par
./analyze -in ${PANDAROOT}/macro/lmd/lumi.misalign.par -out ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/LumiAlignConst.txt -new ${PANDAROOT}/macro/lmd/lumi.misalign_after.par

## change old params for new params
mv  ${PANDAROOT}/macro/lmd/lumi.misalign.par  ${PANDAROOT}/macro/lmd/lumi.misalign_before.par
mv  ${PANDAROOT}/macro/lmd/lumi.misalign_after.par ${PANDAROOT}/macro/lmd/lumi.misalign.par

##save results in good storage place
cd ${PANDAROOT}/macro/lmd
mkdir tmpOutputAlignTMP/results/misalign100mkmDOF111000
cp ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/Lumi_out_MC_and_REC_trks_matches_with_IDs0_before.root
cp ${PANDAROOTmy}/myKnossos/Results.root ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/Results.root
cp ${PANDAROOT}/macro/lmd/lumi.misalign_before.par ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/.
cp ${PANDAROOT}/macro/lmd/lumi.misalign.par ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/lumi.misalign_after.par
cp ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/ResidualsHist.root ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/ResidualsHist_before.root
rm ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/*


##repeat rec with new params
time root -l -b -q 'runLumi0SimBox.C(1000,11.91,"tmpOutputAlignTMP")'
time root -l -b -q 'runLumi1Digi.C(1000,0,"tmpOutputAlignTMP")'
time root -l -b -q 'runLumi2Reco.C(1000,0,"tmpOutputAlignTMP")' >> REC_TESTmisalign100mkmDOF111000_2.log
time root -l -b -q 'runLumi3Finder.C(1000,0,"tmpOutputAlignTMP", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(1000,0,"tmpOutputAlignTMP")'
time root -l -b -q 'runLumi5Geane.C(1000,11.91,0,"tmpOutputAlignTMP")'

cd ${PANDAROOT}/build/bin
##obtain information about resolution after alignment
./rec_mc_match -s 0 -n 1000 -mom 11.91 -path ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP
cp ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/Lumi_out_MC_and_REC_trks_matches_with_IDs0_after.root
##obtain info about hits for alignment [here just for check resuduals after alignment procedure]
./hits_align -s 0 -n 1000 -path ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP -out ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/TrackForAlign.txt -outhist ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/ResidualsHist.root -v 0
##save results in good storage place
cp ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/ResidualsHist.root ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/ResidualsHist_after.root 
cd  ${PANDAROOT}/macro/lmd
##obtain summary plots
time root -l -b -q GenAlignEffect.C\(\"${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/\",100,0,1,\"${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/Sens\"\)

exit
