#!/bin/bash
PANDAROOT=/PANDA/pandaroot
PANDAROOTmy=/PANDA/karavdina
# #----------------------------------------------------------------------
path=${PANDAROOT}/macro/lmd/tmpOutputAlignTMP

mkdir ${path}

numTrks=1
mergedHits=true
numEv=10000
pbeam=15
dr=100
da=0

#TRANS=(0 50 100 150 200 250 300 400 500 600 700 800 900 1000 1500) #mkm
#TRANS=(600 700 800 900 1000) #mkm
#TRANS=(0 100 200 300 400 500 600 700 800 900 1000) #mkm
TRANS=(0 200) #mkm
TRANSN=${#TRANS[@]}
#ROT=(0 1 3 5 7 9) #mrad
ROT=(0 3) #mrad
ROTN=${#ROT[@]}
##ITTER=(1)
##ITTERN=${#ITTER[@]}
for (( jt=0;jt<$TRANSN;jt++)); do
 for (( jr=0;jr<$ROTN;jr++)); do
     dr=${TRANS[${jt}]}
     da=${ROT[${jr}]}
     path_res=${path}/results_${dr}mkm_${da}mrad_${numEv}events
     mkdir ${path_res}
     cd ${PANDAROOT}/macro/lmd/
##Full sim & rec
seedsim=$RANDOM
 root -l -b -q runLumiPixel0SimBox.C\(${numEv},0,${pbeam},"\"${path}\"",0,-2212,${numTrks}\)
 root -l -b -q runLumiPixel1Digi.C\(${numEv},0,"\"${path}\""\)
rm ${PANDAROOT}/macro/lmd/lumi.misalign_pixel.par

root -l -b -q LMD_alignment/create_misalignment_lmd_pixel.C\(${dr},${da},"\"${PANDAROOT}/macro/lmd/lumi.misalign_pixel.par\""\)
root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\""\)
### Merge hits
root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\)
# ### CA can use merged or single(not merged) hits
# ### change "CA" --> "Follow" if you want to use Trk-Following as trk-search algorithm
# ### NB: Trk-Following can't use single(not merged) hits!
# ### change true --> false if you don't want to use missing search algorithm
  trkCuts=false
  root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits},${trkCuts}\)
   
 ##Miniut
    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
### or Kalman Fillter
### root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\)
    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)

    cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1 -mh 0 -v 0 -path ${path}
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  ${path_res}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_${dr}_da_${da}_before.root

   ##alignment iterations
  ##  for (( it=0;it<$ITTERN;it++)); do
##	nit=${ITTER[${it}]}
	rm  ${path}/hits_trk_for_alignment*
   ##obtain info about hits for alignment
##	./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 99 -out ${path}/hits_trk_for_alignment.txt -outhist ${path_res}/hitsRes_before_alignment_${nit}itter.root

    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 0 -out ${path}/hits_trk_for_alignment_sector0.txt -outhist ${path_res}/hitsRes_before_alignment_sector0.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 1 -out ${path}/hits_trk_for_alignment_sector1.txt -outhist ${path_res}/hitsRes_before_alignment_sector1.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 2 -out ${path}/hits_trk_for_alignment_sector2.txt -outhist ${path_res}/hitsRes_before_alignment_sector2.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 3 -out ${path}/hits_trk_for_alignment_sector3.txt -outhist ${path_res}/hitsRes_before_alignment_sector3.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 4 -out ${path}/hits_trk_for_alignment_sector4.txt -outhist ${path_res}/hitsRes_before_alignment_sector4.root

    # cd ${path}
    #cat hits_trk_for_alignment_sector0.txt hits_trk_for_alignment_sector1.txt hits_trk_for_alignment_sector2.txt hits_trk_for_alignment_sector3.txt hits_trk_for_alignment_sector4.txt > hits_trk_for_alignment.txt
   ##do alignment
   cd ${PANDAROOTmy}/myKnossos
   rm ${path_res}/logKnossos*
   cp constantsLMD.h ${path_res}/.
   #./knossos -i ${path}/hits_trk_for_alignment.txt -o ${path}/LumiAlignConst.txt -n ${numEv} -r 1 >> ${path_res}/logKnossos_${nit}itter

   ./knossos -i ${path}/hits_trk_for_alignment_sector0.txt -o ${path}/LumiAlignConst_sector0.txt -n ${numEv} -r 1 >> ${path_res}/logKnossos0
   ./knossos -i ${path}/hits_trk_for_alignment_sector1.txt -o ${path}/LumiAlignConst_sector1.txt -n ${numEv} -r 1 >> ${path_res}/logKnossos1
   ./knossos -i ${path}/hits_trk_for_alignment_sector2.txt -o ${path}/LumiAlignConst_sector2.txt -n ${numEv} -r 1 >> ${path_res}/logKnossos2
   ./knossos -i ${path}/hits_trk_for_alignment_sector3.txt -o ${path}/LumiAlignConst_sector3.txt -n ${numEv} -r 1 >> ${path_res}/logKnossos3
   ./knossos -i ${path}/hits_trk_for_alignment_sector4.txt -o ${path}/LumiAlignConst_sector4.txt -n ${numEv} -r 1 >> ${path_res}/logKnossos4
   rm  ${path}/LumiAlignConst.txt
   cat ${path}/LumiAlignConst_sector0.txt ${path}/LumiAlignConst_sector1.txt ${path}/LumiAlignConst_sector2.txt ${path}/LumiAlignConst_sector3.txt ${path}/LumiAlignConst_sector4.txt > ${path}/LumiAlignConst.txt

   # cp ${path}/LumiAlignConst_sector0.txt ${path}/LumiAlignConst.txt
   # head -28 ${path}/LumiAlignConst_sector1.txt >> ${path}/LumiAlignConst.txt
   # head -28 ${path}/LumiAlignConst_sector2.txt >> ${path}/LumiAlignConst.txt
   # head -28 ${path}/LumiAlignConst_sector3.txt >> ${path}/LumiAlignConst.txt
   # head -28 ${path}/LumiAlignConst_sector4.txt >> ${path}/LumiAlignConst.txt

   #obtain results and write it in new *.par file
   rm ${path_res}/lumi.misalign_pixel_after.par
   head -16 ${PANDAROOT}/macro/lmd/lumi.misalign_pixel.par >> ${path_res}/lumi.misalign_pixel_after.par

     cd ${VMCWORKDIR}/build/bin
   ./analyze_alignment -in ${PANDAROOT}/macro/lmd/lumi.misalign_pixel.par -out ${path}/LumiAlignConst.txt -new ${path_res}/lumi.misalign_pixel_after.par -outroot ${path_res}/KnossosResults.root

## change old params for new params
mv  ${PANDAROOT}/macro/lmd/lumi.misalign_pixel.par  ${path_res}/lumi.misalign_pixel_before.par
cp  ${path_res}/lumi.misalign_pixel_after.par ${PANDAROOT}/macro/lmd/lumi.misalign_pixel.par

# ##clean tmp storage place
#rm ${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/*
rm ${path}/*

# ##repeat rec with new params
cd ${PANDAROOT}/macro/lmd/
##Full sim & rec
root -l -b -q runLumiPixel0SimBox.C\(${numEv},0,${pbeam},"\"${path}\"",0,-2212,${numTrks}\)
root -l -b -q runLumiPixel1Digi.C\(${numEv},0,"\"${path}\""\)
root -l -b -q runLumiPixel2Reco.C\(${numEv},0,"\"${path}\""\)
### Merge hits
root -l -b -q runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\)
### CA can use merged or single(not merged) hits
### change "CA" --> "Follow" if you want to use Trk-Following as trk-search algorithm
### NB: Trk-Following can't use single(not merged) hits!
### change true --> false if you don't want to use missing search algorithm
   ## if [ ${nit} -lt ${ITTERN} ] 
  ##  then 
##	trkCuts=false
  ##  else 
##	trkCuts=true 
  ##  fi
    trkCuts=true 
root -l -b -q runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",true,${mergedHits},${trkCuts}\)
   
 ##Miniut
    root -l -b -q runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,${mergedHits}\)
### or Kalman Fillter
### root -l -b -q runLumi4KalmanFitter.C\(${numEv},0,"\"${path}\"",0,1,${mergedHits}\)
    root -l -b -q runLumi5Geane.C\(${numEv},${pbeam},0,"\"${path}\"",0,${mergedHits}\)

     cd ${VMCWORKDIR}/build/bin
    ./rec_mc_match -s 0 -n ${numEv} -t ${numTrks} -mom ${pbeam} -npx 1 -mh 0 -v 0 -path ${path}
    mv ${path}/Lumi_out_MC_and_REC_trks_matches_with_IDs0.root  ${path_res}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_${dr}_da_${da}_after.root
   # ##obtain info about hits for alignment
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 0 -out ${path}/hits_trk_for_alignment_sector0_after.txt -outhist ${path_res}/hitsRes_after_alignment_sector0.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 1 -out ${path}/hits_trk_for_alignment_sector1_after.txt -outhist ${path_res}/hitsRes_after_alignment_sector1.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 2 -out ${path}/hits_trk_for_alignment_sector2_after.txt -outhist ${path_res}/hitsRes_after_alignment_sector2.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 3 -out ${path}/hits_trk_for_alignment_sector3_after.txt -outhist ${path_res}/hitsRes_after_alignment_sector3.root
    ./hits_align_pixel -s 0 -n ${numEv} -path ${path} -m 4 -out ${path}/hits_trk_for_alignment_sector4_after.txt -outhist ${path_res}/hitsRes_after_alignment_sector4.root
##    done


# # # # # # # # ##obtain summary plots
# # # # # # # # time root -l -b -q GenAlignEffect.C\(\"${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/misalign100mkmDOF111000/\",100,0,1,\"${PANDAROOT}/macro/lmd/tmpOutputAlignTMP/results/Sens\"\)
    cd ${PANDAROOT}/macro/lmd/LMD_alignment
    #compare theta resolution hists with reference hist
    cp ${path}/results_0mkm_0mrad_${numEv}events/Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_0_da_0_before.root  tuples/.
    cp ${path_res}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_${dr}_da_${da}_after.root tuples/.
    root -b -l -q "stat_analyzer.C+(\"Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_0_da_0_before\", \"Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_${dr}_da_${da}_after\")" >> ${path_res}/logCOMPAREthetaRes

    cp ${path_res}/Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_${dr}_da_${da}_before.root tuples/.
    root -b -l -q "stat_analyzer.C+(\"Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_0_da_0_before\", \"Lumi_out_MC_and_REC_trks_matches_with_IDs0_dr_${dr}_da_${da}_before\")" >> ${path_res}/logCOMPAREthetaRes

    #combine all important outputs in one pdf file
    root -l -b -q SummaryAlign.C\("\"${path_res}\"",${dr},${da}\)  >> ${path_res}/logSummary
##    cp ${path_res}/ResultsSummary_*.root /PANDA/karavdina/web/data/.
    cp ${path_res}/ResultsSummary* /PANDA/results/alignmentTEST/.
 done
done

exit














