#!/bin/bash
# mkdir  /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign/results      
# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_0_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_0_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_0_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0005,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_5_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_5_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_5_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0010,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_10_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'  >> REC_10_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_10_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0020,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_20_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_20_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_20_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0050,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_50_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_50_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_50_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'create_misalignment_lumi.C(0.01,0)'
cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_100_0.par
time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_100_0.log
time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
cd /data/FAIRsorf/pandaroot/build/bin
./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
./hits_align -s 0 -n 10000 -path /home/akaravdina/lmdMacro/tmpOutputAlign -out /home/akaravdina/lmdMacro/tmpOutputAlign/TrackForAlign.txt -v 0
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_100_0.root 
cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
#rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.02,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_200_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_200_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_200_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.05,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_500_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_500_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_500_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.1,0)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_1000_0.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_1000_0.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_1000_0.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*
# #################################################

# # angle = 0.5 mrad
# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_0_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_5_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_0_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0005,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_5_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_5_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_5_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0010,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_10_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")' >> REC_10_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_10_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0020,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_20_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'  >> REC_20_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_20_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0050,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_50_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'  >> REC_50_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_50_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.01,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_100_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'  >> REC_100_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_100_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.02,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_200_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'  >> REC_200_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_200_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.05,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_500_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'  >> REC_500_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_500_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.1,0.0005)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_1000_0.5.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'  >> REC_1000_5.log
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_1000_0.5.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# #######################################################################
# #angle = 1 mrad
# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_0_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_0_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0005,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_5_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_5_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0010,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_10_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_10_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0020,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_20_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_20_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.0050,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_50_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_50_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.01,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_100_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_100_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.02,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_200_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_200_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.05,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_500_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_500_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'create_misalignment_lumi.C(0.1,0.001)'
# cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_1000_1.par
# time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# cd /data/FAIRsorf/pandaroot/build/bin
# ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_1000_1.root 
# cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# rm tmpOutputAlign/*

# # ##############################################################
# # #angle = 10 mrad
# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_0_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_0_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0.0005,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_5_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_5_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0.0010,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_10_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_10_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0.0020,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_20_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_20_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0.0050,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_50_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_50_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0.01,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_100_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_100_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0.02,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_200_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_200_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'create_misalignment_lumi.C(0.05,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_500_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_500_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # time root -l -b -q 'runLumi0SimBox.C(10000,11.91,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi1Digi.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'create_misalignment_lumi.C(0.1,0.01)'
# # cp lumi.misalign.par tmpOutputAlign/results/lumi.misalign_1000_10.par
# # time root -l -b -q 'runLumi2Reco.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi3Finder.C(10000,0,"tmpOutputAlign", 0, "CA",true)'
# # time root -l -b -q 'runLumi4Fitter.C(10000,0,"tmpOutputAlign")'
# # time root -l -b -q 'runLumi5Geane.C(10000,11.91,0,"tmpOutputAlign")'
# # cd /data/FAIRsorf/pandaroot/build/bin
# # ./rec_mc_match -s 0 -n 10000 -mom 11.91 -path "/data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign"
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/tmpOutputAlign
# # cp Lumi_out_MC_and_REC_trks_matches_with_IDs0.root results/Lumi_out_MC_and_REC_trks_matches_with_IDs_1000_10.root 
# # cd /data/FAIRsorf/pandaroot/trunk/macro/lmd/
# # rm tmpOutputAlign/*

# # #rm TracksHits.txt
# # #time root -l -b -q 'AlignmentStudies.C(5000,0,"tmpOutputAlign")' >> TracksHits.txt

exit
