/*
 * ModelParameterHandler.h
 *
 *  Created on: Mar 19, 2013
 *      Author: steve
 */

#ifndef MODELPARAMETERHANDLER_H_
#define MODELPARAMETERHANDLER_H_

#include "ModelParSet.h"
#include "Parametrization.h"
#include "ParametrizationModel.h"
#include "ParametrizationProxy.h"

#include <map>
#include <set>
#include <memory>

class ModelParameterHandler {
private:
  /**
   * The parameter set of the model.
   */
  ModelParSet model_par_set;

  /**
   * Map of ParametrizationProxys, which is either a Parametrization or a
   * ParametrizationModel, for every ModelPar of this Model that is being
   * parametrized.
   */
  std::map<const std::shared_ptr<ModelPar>, ParametrizationProxy> parametrizations;

  /**
   * Set of model parametrizations that are called at each iteration step to
   * update parameters due to connections to free parameters that have changed.
   * This set can only be equal to the full set of parametrizations or less.
   * Since ParametrizationModels already update on each iteration, this
   * procedure is not required for them.
   */
  std::set<std::shared_ptr<Parametrization> > updating_parametrizations;

public:
  ModelParameterHandler();
  virtual ~ModelParameterHandler();

  ModelParSet& getModelParameterSet();

  int checkParametrizations() const;

  int checkParameters();

  void registerUpdaters();

  void reinitModelParametrizations();

  void executeParametrizationModels(double *x);


  void registerParametrization(std::shared_ptr<ModelPar> model_par, std::shared_ptr<Parametrization> parametrization);

  void registerParametrizations(ModelParSet &model_par_set_, std::shared_ptr<Parametrization> parametrization);

  void registerParametrizationModel(std::shared_ptr<ModelPar> model_par, std::shared_ptr<ParametrizationModel> parametrization_model);

  void registerParametrizationModels(ModelParSet &model_par_set_, std::shared_ptr<ParametrizationModel> parametrization_model);


  /**
   * This method updates the model parameters that are not fixed (free) by the
   * ones in the array pars. This has to be called once after each minimizer
   * iteration step. The correspondence is secured by the fact that the array is
   * generated by the model itself in the beginning, so in other words it knows
   * which parameter in the array corresponds to which ModelPar in the parameter
   * set.
   */
  void updateModelParameters(const double *pars);
};

#endif /* MODELPARAMETERHANDLER_H_ */
