/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef CS_TH
#define CS_TH

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class cs_th : public RooAbsPdf {
public:
  cs_th() {} ; 
  cs_th(const char *name, const char *title,
	      RooAbsReal& _th,
	   //   RooAbsReal& _L,
	      RooAbsReal& _Sigtot,
	      RooAbsReal& _B,
	      RooAbsReal& _Rho,
	      double _Plab);
  cs_th(const cs_th& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new cs_th(*this,newname); }
 // Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
 // Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  inline virtual ~cs_th() { }

  Double_t evaluate(Double_t x) const ;
  //virtual Bool_t selfNormalized() const {return kTRUE;};

protected:

  RooRealProxy th ;
  //RooRealProxy L ;
  RooRealProxy Sigtot ;
  RooRealProxy B ;
  RooRealProxy Rho ;

   double M;
   double Plab;
   double Elab;
   double S;
   double pcm2;
   double gamma;
   double beta;
   double lnP;
   double pi;
   double hbarc2;
   double alpha;
   double pkoef;
   double dt;
  
  Double_t evaluate() const ;

private:

  ClassDef(cs_th,1) // Your description goes here...
};
 
#endif
