#BSUB -o mpi.out
#BSUB -e mpi.err
#BSUB -n 3
#
# Example job description file for LSF batch farm
#
 
NPROC=7
RUNDIR=$HOME/bin
PROG=boss_worker_mpi
ARGS="-j $HOME/jobs/jobs.in -v"

rm -f $RUNDIR/nodes_lsf
for host in $LSB_HOSTS
do
  echo $host >> $RUNDIR/nodes_lsf
done
 
echo ---------------------------------------------------------------------------
echo Ready to run $PROG on $LSB_HOSTS
echo mpirun -v -np $NPROC -machinefile $RUNDIR/nodes_lsf $RUNDIR/$PROG $ARGS 
echo ---------------------------------------------------------------------------

mpirun -v -np $NPROC -machinefile $RUNDIR/nodes_lsf $RUNDIR/$PROG $ARGS
