void DrawTestTimeBased(){
  	TString fname = "/panda/myResults/ONLINE/DPM_el_inel_1_5/Sample0/Lumi_DigisQA_0.root";
  //	TString fname = "/panda/myResults/ONLINE/DPM_el_inel_1_5/Lumi_DigisQA_0.root";
	TFile * fin = new TFile(fname,"READ");
	TTree *tdigiQA = (TTree*)fin->Get("cbmsim");
	int tIntrate = 40;
	TH1 *htpl0_sig = new TH1I("htpl0_sig",";time, ns; fired pixels",100*tIntrate,0,100*tIntrate);
	TH1 *htpl1_sig = new TH1I("htpl1_sig",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	TH1 *htpl2_sig = new TH1I("htpl2_sig",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	TH1 *htpl3_sig = new TH1I("htpl3_sig",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	tdigiQA->Project("htpl0_sig","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==0 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==1");
	tdigiQA->Project("htpl1_sig","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==1 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==1");
	tdigiQA->Project("htpl2_sig","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==2 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==1");
	tdigiQA->Project("htpl3_sig","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==3 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==1");
	htpl0_sig->SetLineWidth(2);
	htpl1_sig->SetLineWidth(2);
	htpl2_sig->SetLineWidth(2);
	htpl3_sig->SetLineWidth(2);
	htpl0_sig->SetLineColor(1);
	htpl1_sig->SetLineColor(2);
	htpl2_sig->SetLineColor(3);
	htpl3_sig->SetLineColor(4);


	TCanvas *c1 = new TCanvas ("digiQA_ns","digiQA_25ns",600,800);
	c1->Divide(1,3);
	c1->cd(2);
	TLegend *leg_sig = new TLegend(0.78,0.75,0.98,0.95);
	leg_sig->AddEntry(htpl0_sig,"pl#0 (side#0), el.","l");
	leg_sig->AddEntry(htpl1_sig,"pl#1 (side#0), el.","l");
	leg_sig->AddEntry(htpl2_sig,"pl#2 (side#0), el.","l");
	leg_sig->AddEntry(htpl3_sig,"pl#3 (side#0), el.","l");
	htpl2_sig->Draw();
	htpl3_sig->Draw("same");
	htpl1_sig->Draw("same");
	htpl0_sig->Draw("same");
	leg_sig->Draw();

	c1->cd(1);
	TH1 *htpl0_all = new TH1I("htpl0_all",";time, ns; fired pixels",100*tIntrate,0,100*tIntrate);
	TH1 *htpl1_all = new TH1I("htpl1_all",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	TH1 *htpl2_all = new TH1I("htpl2_all",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	TH1 *htpl3_all = new TH1I("htpl3_all",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	tdigiQA->Project("htpl0_all","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==0 && LMDPixelDigisQ.fSide==0");
	tdigiQA->Project("htpl1_all","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==1 && LMDPixelDigisQ.fSide==0");
	tdigiQA->Project("htpl2_all","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==2 && LMDPixelDigisQ.fSide==0");
	tdigiQA->Project("htpl3_all","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==3 && LMDPixelDigisQ.fSide==0");
	htpl0_all->SetLineWidth(2);
	htpl1_all->SetLineWidth(2);
	htpl2_all->SetLineWidth(2);
	htpl3_all->SetLineWidth(2);
	htpl0_all->SetLineColor(1);
	htpl1_all->SetLineColor(2);
	htpl2_all->SetLineColor(3);
	htpl3_all->SetLineColor(4);
	TLegend *leg_all = new TLegend(0.78,0.75,0.98,0.95);
	leg_all->AddEntry(htpl0_all,"pl#0 (side#0), el.+inel.","l");
	leg_all->AddEntry(htpl1_all,"pl#1 (side#0), el.+inel.","l");
	leg_all->AddEntry(htpl2_all,"pl#2 (side#0), el.+inel.","l");
	leg_all->AddEntry(htpl3_all,"pl#3 (side#0), el.+inel.","l");
	htpl3_all->Draw();
	htpl2_all->Draw("same");
	htpl1_all->Draw("same");
	htpl0_all->Draw("same");
	leg_all->Draw();

	c1->cd(3);
	TH1 *htpl0_bkg = new TH1I("htpl0_bkg",";time, ns; fired pixels",100*tIntrate,0,100*tIntrate);
	TH1 *htpl1_bkg = new TH1I("htpl1_bkg",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	TH1 *htpl2_bkg = new TH1I("htpl2_bkg",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	TH1 *htpl3_bkg = new TH1I("htpl3_bkg",";time, ns; fired pixels",100*tIntrate,0*tIntrate,100*tIntrate);
	tdigiQA->Project("htpl0_bkg","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==0 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==0");
	tdigiQA->Project("htpl1_bkg","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==1 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==0");
	tdigiQA->Project("htpl2_bkg","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==2 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==0");
	tdigiQA->Project("htpl3_bkg","LMDPixelDigisQ.fEvTime","LMDPixelDigisQ.fPl==3 && LMDPixelDigisQ.fSide==0 && LMDPixelDigisQ.fSigfl==0");
	htpl0_bkg->SetLineWidth(2);
	htpl1_bkg->SetLineWidth(2);
	htpl2_bkg->SetLineWidth(2);
	htpl3_bkg->SetLineWidth(2);
	htpl0_bkg->SetLineColor(1);
	htpl1_bkg->SetLineColor(2);
	htpl2_bkg->SetLineColor(3);
	htpl3_bkg->SetLineColor(4);
	TLegend *leg_bkg = new TLegend(0.78,0.75,0.98,0.95);
	leg_bkg->AddEntry(htpl0_bkg,"pl#0 (side#0), inel.","l");
	leg_bkg->AddEntry(htpl1_bkg,"pl#1 (side#0), inel.","l");
	leg_bkg->AddEntry(htpl2_bkg,"pl#2 (side#0), inel.","l");
	leg_bkg->AddEntry(htpl3_bkg,"pl#3 (side#0), inel.","l");
	htpl3_bkg->Draw();
	htpl2_bkg->Draw("same");
	htpl1_bkg->Draw("same");
	htpl0_bkg->Draw("same");
	leg_bkg->Draw();
}
