#!/bin/bash 
################################################################
## script for running sim&rec for LMD with BOX generarot
## [with pixels sensors set-up!]
## 13/11/2012 1st version
## 06/09/2013 updated version
## A.Karavdina
################################################################
echo Enter momentum from "1.5, 4.06, 8.9, 11.91, 15 [GeV/c]":
read mom
echo "Beam mometum is: $mom!"
cd ${VMCWORKDIR}/macro/lmd/
pbeam=$mom


momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`
#path=${VMCWORKDIR}/macro/lmd/testDPMDirect/LMDboxRealVacuum/mom_${momStr}/
path=${VMCWORKDIR}/macro/lmd/Anastasia/tests/DPM_sep2013/output_direct/mom_${momStr}/
mkdir -p ${path}
#number of trks per event
numTrks=1
#merge hits on sensors from different sides. true=yes
mergedHits=true
#number of events
numEv=20000
# #add multiples scattering error estimation for hits. false=no
useMSerr=false

# #simulation with DPM Direct

cd ${VMCWORKDIR}/macro/lmd/Anastasia/tests/DPM_sep2013/
    root -l -b -q runLumiPixel0SimDPMDirect.C\(${numEv},0,${pbeam},"\"${path}\"",23465,0\) &> ${path}/logDPM_direct


