{
  gSystem->AddIncludePath("-I$VMCWORKDIR/emc");
  gSystem->AddIncludePath("-I$VMCWORKDIR/emc/EmcDigi");
  gSystem->AddIncludePath("-I$VMCWORKDIR/emc/EmcMC");
  gSystem->AddIncludePath("-I$VMCWORKDIR/emc/EmcTools");
  gSystem->AddIncludePath("-I$VMCWORKDIR/emc/EmcReco");
  gSystem->AddIncludePath("-I$VMCWORKDIR/emc/EmcData");
  gSystem->AddIncludePath("-I$VMCWORKDIR/tof");
  gSystem->AddIncludePath("-I$VMCWORKDIR/tpc");
  gSystem->AddIncludePath("-I$VMCWORKDIR/rho");
  gSystem->AddIncludePath("-I$VMCWORKDIR/lhetrack");
  gSystem->AddIncludePath("-I$VMCWORKDIR/rho/RhoBase");
  gSystem->AddIncludePath("-I$VMCWORKDIR/drc");
  gSystem->AddIncludePath("-I$VMCWORKDIR/mvd/MvdData");
  gSystem->AddIncludePath("-I$VMCWORKDIR/mvd");
  gSystem->AddIncludePath("-I$VMCWORKDIR/pnddata");
  gSystem->AddIncludePath("-I$VMCWORKDIR/base");
  gSystem->AddIncludePath("-I$VMCWORKDIR/trackbase");
  gSystem->AddIncludePath("-I/home/vanni/TMVA/include");
  gSystem->AddIncludePath("-I$VMCWORKDIR/gpid");
  gSystem->AddIncludePath("-I$VMCWORKDIR/PndTools/MVA/LVQ1");
  gROOT->LoadMacro("$VMCWORKDIR/gconfig/basiclibs.C");
  basiclibs();
  gSystem->Load("libGeoBase");
  gSystem->Load("libParBase");
  gSystem->Load("libBase");
  gSystem->Load("libField");
  gSystem->Load("libGen");
  gSystem->Load("libPassive");
  gSystem->Load("libEmc"); 
  gSystem->Load("libGeom.so");
  gSystem->Load("libPndData.so");
  //gSystem->Load("libPndBase.so");
  gSystem->Load("libGui.so");
  gSystem->Load("libgenfit");
  gSystem->Load("libtpc");
  gSystem->Load("libTof");
  gSystem->Load("libDrcProp");
  gSystem->Load("libDrc");
  //  gSystem->Load("libtpcreco");
  gSystem->Load("libtrackrep");
  gSystem->Load("libTrkBase");
  //  gSystem->Load("librecotasks");
  //gSystem->Load("libMvd");
  // gSystem->Load("libMvdReco");
  //gSystem->Load("libLHETrack");
  gSystem->Load("libRho");
  gSystem->Load("libGeane");
  gSystem->Load("libTMVA");
  gSystem->Load("libMva");
  gSystem->Load("libGpid");
  
  gStyle->SetPalette(1);
  gStyle->SetTitleStyle(0);
  gStyle->SetTitleXSize(0.06);
  gStyle->SetTitleYSize(0.06);
  gStyle->SetCanvasColor(kWhite);
  gStyle->SetFrameFillColor(kWhite);
  gStyle->SetOptStat(0);
  delete gRandom;
  gRandom=new TRandom3(0);
}
