

###################
PROJECT(alignment)
#SET(CMAKE_VERBOSE_MAKEFILE ON)
cmake_minimum_required(VERSION 2.4)

INCLUDE_DIRECTORIES($ENV{ROOTSYS}/include)
LINK_DIRECTORIES(../../)


SET(SOURCES main.cpp ../../src/TChough2.cxx)


EXEC_PROGRAM(
		$ENV{ROOTSYS}/bin/root-config
		ARGS --glibs --cflags
		OUTPUT_VARIABLE ROOTCONFIG)
		
SET(ROOT_LIBS ${ROOTCONFIG})

SET(CMAKE_CXX_FLAGS "-g -Wall -Wno-long-long")


ADD_EXECUTABLE(testHough ${SOURCES})
TARGET_LINK_LIBRARIES(testHough ${ROOT_LIBS})
TARGET_LINK_LIBRARIES(testHough testChamber)
SET_TARGET_PROPERTIES(testHough PROPERTIES LINKER_LANGUAGE CXX)
