inFile = eventTrees/clusterTree.root
outFile= eventTrees/patRecTree.root
alignmentFile = alignments/al0.txt
histFile= hists/clusterHist.root
mode=maxAmp
#mode maxAmp, eventDisp, hough
houghThreshold=4
houghDepth=6
#cut sigma a0/a2 a1/2 cutMinU cutMaxU
