inFile = eventTrees/clusterTree8sigma.root
outFile= eventTrees/patRecTree2.root
alignmentFile = alignments/al1.txt
histFile= hists/clusterHist2.root
mode=hough
#mode maxAmp, eventDisp, hough
houghThreshold=4
houghDepth=5
#cut sigma a0/a2 a1/2 cutMinU cutMaxU
