inFile = eventTrees/clM1.root
outFile= eventTrees/prM11.root
alignmentFile = alignments/alMasterSun0.txt
histFile= pr090930_1.root
mode=maxAmp
debug=false
#mode maxAmp, eventDisp, hough
houghThreshold=3
houghDepth=6
#cut sigma a0/a2 a1/2 cutMinU cutMaxU
