#!/bin/bash 
################################################################
## script for running sim&rec for LMD with BOX generarot
## [with pixels sensors set-up!]
## 13/11/2012 1st version
## 06/09/2013 updated version
## A.Karavdina
################################################################
echo Enter momentum from "1.5, 4.06, 8.9, 11.91, 15 [GeV/c]":
read mom
echo "Beam mometum is: $mom!"
cd ${VMCWORKDIR}/macro/lmd/
pbeam=$mom
# ### pick up half solenoid maps for 1.5 GeV/c [tmp, should be removed one day!] ###
# solsw=3 #GeV, switch between half and full solenoid: below half of solenoid
# if [[ $(echo "if (${pbeam} > ${solsw}) 1 else 0" | bc) -eq 1 ]]; then
#     echo "FULL solenoid field maps"
#     ln -sf ${VMCWORKDIR}/macro/lmd/Anastasia/solenoid_fc/* ${VMCWORKDIR}/input/.
# else
#     echo "HALF solenoid field maps"
#     ln -sf ${VMCWORKDIR}/macro/lmd/Anastasia/solenoid_hc/* ${VMCWORKDIR}/input/.
# fi
# ######################################################
for zT in 20 50
do

momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`
path=${VMCWORKDIR}/macro/lmd/Anastasia/tests/RestGas/testRestGas_z_${zT}cm/mom_${momStr}/

mkdir -p ${path}
#number of trks per event
numTrks=1
#number of events
numEv=1000000
#numEv=100

##############
# set flags

##merge hits on sensors from different sides. true=yes
mergedHits=true

##Skip kinematic filter (before back-propagation)
SkipFilt=false
### if SkipFilt=false (XThetaCut or YPhiCut) or BoxCut should be true:
### X-Theta kinematic cut before back-propagation
XThetaCut=true
### Y-Phi kinematic cut before back-propagation
YPhiCut=true
### BOX cut before back-propagation
BoxCut=false

## Clean after back-propagation (momentum or MVA cut)
CleanSig=false

## Write all MC info in TrkQA array
WrAllMC=true

## skip reconstruction (test on already available data)
SkipRec=false
##############

# #simulation with Box generator
root -l -b -q ${VMCWORKDIR}/macro/lmd/Anastasia/tests/RestGas/runLumiPixel0SimBoxTarget.C\(${numEv},0,"\"${path}\"",0,-2212,${pbeam},${numTrks},3562,${zT}\) 

# # #simulation with DPM
#   #  modeDPM=0 #inel
# #    modeDPM=1 #el+inel
if [ $SkipRec == "false" ]; then 
 #   modeDPM=2 #el
#   root -l -b -q runLumiPixel0SimDPMDirectNOdipole.C\(${numEv},0,${pbeam},"\"${path}\"",0,35162,$modeDPM,0.12\) 
#  root -l -b -q runLumiPixel0SimBoxNOdipole.C\(${numEv},0,"\"${path}\"",0,-2212,${pbeam}\) 
# #digi
     root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel1Digi.C\(${numEv},0,"\"${path}\"",0\) 
# #hit reconstruction
     root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel2Reco.C\(${numEv},0,"\"${path}\"",0,false\) 
# ##merge hits
     root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel2bHitMerge.C\(${numEv},0,"\"${path}\""\)

#switch on "missing plane" search algorithm
	 misspl=true
#use cuts during trk seacrh with "CA". Should be 'false' if sensors missaligned!
	 trkcut=true
### change "CA" --> "Follow" if you want to use Trk-Following as trk-search algorithm
### NB: CA can use merged or single(not merged) hits, Trk-Following can't
     root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel3Finder.C\(${numEv},0,"\"${path}\"",0,"\"CA\"",${misspl},${mergedHits},${trkcut},${pbeam}\)

#track fit: 
### Possible options: "Minuit", "KalmanGeane", "KalmanRK"
       root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel4Fitter.C\(${numEv},0,"\"${path}\"",0,"\"Minuit\"",${mergedHits}\)
#track filter (on number of hits and chi2)
     root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel4aFilter.C\(${numEv},0,"\"${path}\"",0,${mergedHits},${SkipFilt},${XThetaCut},${YPhiCut},${BoxCut}\) 

#save filtered results as standart Track array
     mv ${path}/Lumi_Track_0.root ${path}/Lumi_TrackNotFiltered_0.root 
     cp ${path}/Lumi_TrackFiltered_0.root ${path}/Lumi_Track_0.root

#back-propgation GEANE
### Possible options: "Geane", "RK"
     root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel5BackProp.C\(${numEv},0,"\"${path}\"",0,"\"Geane\"",${mergedHits},${pbeam}\)
 # root -l -b -q Anastasia/tests/RestGas/runLumiPixel5BPtest.C\(${numEv},0,"\"${path}\"",10,"\"Geane\"",${mergedHits},${pbeam}\)
fi 
#clean signal from background (momentum cut or MVA cut)
	 if [ $CleanSig == "true" ]; then 
	     root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel5bCleanSig.C\(${numEv},0,"\"${path}\"",0,${pbeam}\)
	 fi

# # Quality assurance task(s)
      root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel7QA.C\(${numEv},0,"\"${path}\"",0,${pbeam},${CleanSig}\)
      root -l -b -q ${VMCWORKDIR}/macro/lmd/runLumiPixel7TrksQA.C\(${numEv},0,"\"${path}\"",0,${pbeam},${WrAllMC},${CleanSig}\)
#      root -l -b -q ${VMCWORKDIR}/macro/lmd/Anastasia/test_macros/BkgSignalCount.C\("\"${path}\"",${numEv},0\)
  #    root -l -b -q ${VMCWORKDIR}/macro/lmd/Anastasia/test_macros/EffTrks.C\(${numEv},0,"\"${path}\""\)
done
## for trace of back propagation (works only if runLumiPixel5BPtest.C was used!)
# root -l -b -q Anastasia/tests/BPmanySteps/MC_REC_MCLMD.C\("\"${path}\""\)
