#add_subdirectory(sim)
add_subdirectory(mdt)
add_subdirectory(emc)
add_subdirectory(drc)
add_subdirectory(ftof)
add_subdirectory(gem)
add_subdirectory(hyp)
add_subdirectory(mvd)
add_subdirectory(rho)
add_subdirectory(stt)
add_subdirectory(rich)
add_subdirectory(lmd)
add_subdirectory(fsim)
add_subdirectory(evtgen)
add_subdirectory(run3)
add_subdirectory(run4)
add_subdirectory(ftf3)
add_subdirectory(ftf4)
add_subdirectory(dpm3)
add_subdirectory(dpm4)
add_subdirectory(timeOrdered)
