/** FairFilteredPrimaryGenerator.h
 *@author V.Friese  <v.friese@gsi.de>
 *
The FairFilteredPrimaryGenerator is responsible for the handling of the MC input.
Several input generators can be registered to it; these have to be
derived from the FairGenerator class. The FairFilteredPrimaryGenerator defines
position and (optionally) smearing of the primary vertex.
This class should be instantised only once.

19.05.14 Martin Galuska, Katja Kleeberg
Expansion of FairFilteredPrimaryGenerator
including
capabilities of event filtering after event generation and before transport

 **/


#ifndef FairFilteredPrimaryGenerator_H
#define FairFilteredPrimaryGenerator_H

#include "FairPrimaryGenerator.h"

#include "FairEvtFilter.h"
#include "FairEvtFilterParams.h"

#include "TNamed.h"                     // for TNamed
#include "TFile.h"                     // for TFile
#include "FairRunSim.h"

#include "FairGenerator.h"              // for FairGenerator

#include "Riosfwd.h"                    // for ostream
#include "Rtypes.h"                     // for Double_t, Bool_t, Int_t, etc
#include "TObjArray.h"                  // for TObjArray
#include "TVector3.h"                   // for TVector3

#include <iostream>                     // for operator<<, basic_ostream, etc
#include <vector>


class FairGenericStack;
class FairMCEventHeader;
class TF1;
class TIterator;

class FairFilteredPrimaryGenerator : public FairPrimaryGenerator

{

public:

	/** Default constructor. **/
	FairFilteredPrimaryGenerator();


	/** Constructor with name and title **/
	FairFilteredPrimaryGenerator(const char* name, const char* title="Filtered Generator");


	/** Destructor. **/
	virtual ~FairFilteredPrimaryGenerator();

	/** Initialize the generator and filter  (if needed!)*/
	virtual Bool_t Init();

	/** Register filters derived from FairFilter.  **/
	void AndFilter(FairEvtFilter* filter) {
		AddFilter(filter, FairEvtFilter::kAnd, kFALSE);
	}

	void AndNotFilter(FairEvtFilter* filter) {
		AddFilter(filter, FairEvtFilter::kAnd, kTRUE);
	}

	void OrFilter(FairEvtFilter* filter) {
		AddFilter(filter, FairEvtFilter::kOr, kFALSE);
	}

	void OrNotFilter(FairEvtFilter* filter) {
		AddFilter(filter, FairEvtFilter::kOr, kTRUE);
	}

	/** Register a filter derived from FairFilter.  **/
	void AddVetoFilter(FairEvtFilter* filter) {
		if ( ! fVetoFilterList ) {
			std::cout << "Empty fFilterList pointer ! " << std::endl;
			return;
		}
		fVetoFilterList->Add(filter);
		fEventVetoFilterActive = kTRUE;
	}


	/** Public method GenerateEvent
        To be called at the beginning of each event from FairMCApplication.
        Generates an event vertex and calls the ReadEvent methods from the
        registered generators.
	 *@param pStack The particle stack
	 *@return kTRUE if successful, kFALSE if not
	 **/
	virtual Bool_t GenerateEvent(FairGenericStack* pStack);


	TObjArray* GetListOfFilters() { return fFilterList;}

	TObjArray* GetListOfVetoFilters() { return fVetoFilterList;}

	void SetFilterMaxTries(Int_t maxTries=99999)
	{
		if ( maxTries > 0 ){
			fEvtFilterStat.fFilterMaxTries = maxTries;
			std::cout << "FairFilteredPrimaryGenerator: maxTries is now set to " << fEvtFilterStat.fFilterMaxTries << "\n";
		} else {
			std::cout << "\n\n\n  -WARNING from FairFilteredPrimaryGenerator: maxTries must be a positive number! Check your SetFilterMaxTries call!\n\n\n";
		}
	}

	void SetVerbose(Int_t verbose=12){
		if ( verbose >= 0 ){
			fVerbose = verbose;
			std::cout << "FairFilteredPrimaryGenerator: fVerbose is now set to " << verbose << "\n";
		} else {
			std::cout << "\n\n\n  -WARNING from FairFilteredPrimaryGenerator: verbose must be a positive number! Check your SetVerbose call!\n\n\n";
		}
	}

	Int_t GetNumberOfFilterMaxTries(){
		//returns the limiting number for the attempts to find an event that suits your filter
		return fEvtFilterStat.fFilterMaxTries;
	}

	Int_t GetNumberOfGeneratedEvents(){
		//returns the number of events generated by the event generators
		return fEvtFilterStat.fGeneratedEvents;
	}

	Int_t GetNumberOfFilterFailedEvents(){
		// this should return 0 if everything works fine
		// if it returns a value >0 it means that fFilterMaxTries is set too low
		// if it returns a value which is equal to the number of events that you requested, it means that either fFilterMaxTries is set way too low
		// or that the generator does not create such events that you are interested in
		// or that your conditions cannot be satisfied at all (logical error)
		return fEvtFilterStat.fFailedFilterEvents;
	}

	void WriteEvtFilterStatsToRootFile(){
		TFile* outputFile;
		outputFile = FairRunSim::Instance()->GetOutputFile();
		outputFile->cd();
		outputFile->mkdir("FairEvtFilter");
		outputFile->cd("FairEvtFilter");
		fEvtFilterStat.Write();
		outputFile->cd();
	}




protected:
		/**  List of registered veto filters */
	TObjArray*  fVetoFilterList;
	/**  Iterator over veto filter list */
	TIterator*  fVetoFilterIter;      //!
	/**  List of registered filters */
	TObjArray*  fFilterList;
	/**  Iterator over filter list */
	TIterator*  fFilterIter;      //!

	/**containing the parameters that are describing your filter statistic*/
	FairEvtFilterParams fEvtFilterStat;
	/**level of commenting output for your filter implementation, between 0 and 12*/
	Int_t fVerbose;
	/**returns kTRUE if any veto filter is active*/
	Bool_t fEventVetoFilterActive;
	/**returns kTRUE if any filter is active*/
	Bool_t fEventFilterActive;
	/**vector containing the result of the EventMatches methods for every added filter in the corresponding order, different vector for each event*/
	std::vector<Bool_t> filterAcceptEvent;
	// vector containing the logical operations with which the filters should be combined
	// the vector extends automatically by adding a filter
	// use to combine multiple filters via && or ||
	// the expression is evaluated sequentally from the first set filter to the last one disregarding operator priorities
	std::vector<UInt_t> fLogicalFilterOperation;
	// vector determining whether each filter should be negated or not
	// the vector extends automatically by adding a filter
	// first entry represents the negating attribute of the filter which was added at first to *this
	// kTRUE entries negate filters, kFALSE do not
	std::vector<Bool_t> fFilterNegation;


	/** Event number (Set by the filtered primary generator
	 **/
	Int_t fEventNrFiltered;


	// registers a regular (non-veto) filter, not for user to be used, see public methods for user interfaces
	void AddFilter(FairEvtFilter* filter, FairEvtFilter::LogicOp op, Bool_t negateFilter) {
		if ( ! fFilterList ) {
			std::cout << "Empty fFilterList pointer ! " << std::endl;
			return;
		}
		fFilterList->Add(filter);
		fEventFilterActive = kTRUE;
		// add the settings for every new filter
		if(fFilterList->GetEntriesFast()!=1){
			fLogicalFilterOperation.push_back(op);
		}
		fFilterNegation.push_back(negateFilter);
	}


private:
	FairFilteredPrimaryGenerator(const FairFilteredPrimaryGenerator&);
	FairFilteredPrimaryGenerator& operator=(const  FairFilteredPrimaryGenerator&);


	ClassDef(FairFilteredPrimaryGenerator,1);

};

#endif


