#!/bin/bash 
################################################################
## script for running sim with DPM
## 03/12/2013 1st version
## A.Karavdina
################################################################
#echo Enter momentum from "1.5, 4.06, 8.9, 11.91, 15 [GeV/c]":
#read mom
#echo "Beam mometum is: $mom!"
mom=1.5
cd ${VMCWORKDIR}/macro/lmd/Anastasia/tests/DPM_dec2013
pbeam=$mom

momStr=`echo $pbeam | sed -e '{ s/\./_/g; }'`
path=${VMCWORKDIR}/macro/lmd/Anastasia/tests/DPM_dec2013/testDPMDirect/mom_${momStr}/
mkdir -p ${path}
#number of events
numEv=1000

# #simulation with DPM
#   modeDPM=1 #el+inel
    modeDPM=2 #el
    root -l -b -q runLumiPixel0SimDPMDirect.C\(${numEv},0,${pbeam},"\"${path}\"",0,37562,${modeDPM},0.12\) &> ${path}/logDPM_direct
    root -l -b -q read_lmd_MC.C\("\"${path}\""\)
