#$ -wd /tmp
#$ -j y
#$ -V

cd $TMPDIR

. $FAIRLIBDIR"/../config.sh"

data=$VMCWORKDIR"/macro/prod"
_target=$data"/data/"

prefix=M
from=1
to=20
mode=0

if test "$1" != ""; then
  prefix=$1
fi

if test "$2" != ""; then
  from=$2
fi

if test "$3" != ""; then
  to=$3
fi

if test "$4" != ""; then
  mode=$4
fi

root -l -b -q -w $data"/"prod_ana.C\(\"$_target/$prefix\",$from,$to,$mode\)  &> $prefix"_"$from"_"$to"_ana.log"

# Move the data to the persistent storage
cp -v $TMPDIR/$prefix*.root $_target 
cp -v $TMPDIR/$prefix*.log $_target

# Evacuate the log-file
cp -v $SGE_STDOUT_PATH $_target/$JOB_ID.log
