#$ -wd /tmp
#$ -j y
#$ -V

cd $TMPDIR

. $FAIRLIBDIR"/../config.sh"

data=$VMCWORKDIR"/macro/prod"
_target=$data"/data/"

prefix=13
nEvts=1000
pdg=13
mom=10.
mult=1
save=""


if test "$1" != ""; then
  prefix=$1
fi

if test "$2" != ""; then
  nEvts=$2
fi

if test "$3" != ""; then
  pdg=$3
fi

if test "$4" != ""; then
  mom=$4
fi

if test "$5" != ""; then
  mult=$5
fi

if test "$6" != ""; then
  save=$6
fi


outprefix=$TMPDIR"/M"$prefix"_"$SGE_TASK_ID
pidfile=$outprefix"_pid.root"

echo $TMPDIR
root -l -q -b $data"/"prod_sim_pgun.C\(\"$outprefix\",$nEvts,$pdg,$mom,$mult\) &> $outprefix"_sim.log"
root -l -b -q $data"/"prod_dig.C\(\"$outprefix\"\) &> $outprefix"_dig.log"
root -l -b -q $data"/"prod_rec.C\(\"$outprefix\"\) &> $outprefix"_rec.log"
root -l -b -q $data"/"prod_pid.C\(\"$outprefix\"\) &> $outprefix"_pid.log"
root -l -b -q $data"/"quickana.C\(\"$pidfile\",1,\"\",0,\"qapart\",0,0,$SGE_TASK_ID,$pdg\)   &> $outprefix"_ana.log"


# Move the data to the persistent storage
if test "$save" == "saveall"; then
  cp -v $TMPDIR/M*root $_target 
  cp -v $TMPDIR/M*log $_target 
else
  cp -v $TMPDIR/M*_pid.root $_target 
  cp -v $TMPDIR/M*_ana.root $_target 
  cp -v $TMPDIR/M*_pid.log $_target 
  cp -v $TMPDIR/M*_par.root $_target 
fi

# Evacuate the log-file
cp -v $SGE_STDOUT_PATH $_target/$JOB_ID.log

# Clean up
rm $TMPDIR/M*root
rm $TMPDIR/M*log
rm $TMPDIR/Fair*root
